# generated by datamodel-codegen:
#   filename:  session.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class Status(StrEnum):
    """
    The API invocation path completed successfully.
    """

    ok = "ok"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status = Field(
        ..., description="The API invocation path completed successfully."
    )
    service: str = Field(..., description="Stable runtime service identity.")
    version: str = Field(
        ..., description="Version from the deployed service's version manifest."
    )


class Requirement(StrEnum):
    SYNTHETIC_ONLY = "SYNTHETIC_ONLY"
    OFF = "OFF"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    SYNTHETIC_FALLBACK = "SYNTHETIC_FALLBACK"


class State(StrEnum):
    UNKNOWN = "UNKNOWN"
    GRANTED = "GRANTED"
    DENIED = "DENIED"


class ClaimRequirementStateView(BaseModel):
    requirement: Requirement
    state: State


class ClaimsStateView(BaseModel):
    email: ClaimRequirementStateView
    firstName: ClaimRequirementStateView
    lastName: ClaimRequirementStateView
    staticAvatar: ClaimRequirementStateView
    animatedAvatar: ClaimRequirementStateView


class RefreshRequest(BaseModel):
    refreshToken: str


class RefreshResponse(BaseModel):
    claims: ClaimsStateView
    accessToken: str = Field(
        ..., description="Newly issued short-lived access token JWT."
    )
    refreshToken: str = Field(
        ...,
        description="Newly issued refresh token JWT; the presented token has been consumed.",
    )


class IntrospectRequest(BaseModel):
    accessToken: str


class Status1(StrEnum):
    active = "active"
    revoked = "revoked"
    expired = "expired"
    not_found = "not_found"


class IntrospectResponse(BaseModel):
    status: Status1
    recommendedRecheckSeconds: int


class LogoutRequest(BaseModel):
    refreshToken: str


class LogoutResponse(BaseModel):
    revoked: bool


class RevokeAllRequest(BaseModel):
    subject: str = Field(
        ...,
        description="Application-visible sector subject (`sub`) for the account to revoke.",
    )


class RevokeAllResponse(BaseModel):
    revokedCount: int


class Error(BaseModel):
    reason: str
    message: str | None = None
