# generated by datamodel-codegen:
#   filename:  session.yaml

from __future__ import annotations

from enum import Enum, StrEnum

from pydantic import BaseModel, ConfigDict, Field


class Kty(StrEnum):
    RSA = "RSA"


class Use(StrEnum):
    sig = "sig"


class Alg(StrEnum):
    RS256 = "RS256"


class ApplicationJsonWebKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kty: Kty
    n: str = Field(..., description="Base64url-encoded RSA modulus.")
    e: str = Field(..., description="Base64url-encoded RSA public exponent.")
    kid: str = Field(
        ..., description="Stable signing-key identifier copied into JWT JOSE headers."
    )
    use: Use
    alg: Alg


class ApplicationJwksResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    keys: list[ApplicationJsonWebKey]


class Status(StrEnum):
    """
    The API invocation path completed successfully.
    """

    ok = "ok"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status = Field(
        ..., description="The API invocation path completed successfully."
    )
    service: str = Field(..., description="Stable runtime service identity.")
    version: str = Field(
        ..., description="Version from the deployed service's version manifest."
    )


class Requirement(StrEnum):
    SYNTHETIC_ONLY = "SYNTHETIC_ONLY"
    OFF = "OFF"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    SYNTHETIC_FALLBACK = "SYNTHETIC_FALLBACK"


class State(StrEnum):
    UNKNOWN = "UNKNOWN"
    GRANTED = "GRANTED"
    DENIED = "DENIED"


class ClaimRequirementStateView(BaseModel):
    requirement: Requirement
    state: State


class ClaimsStateView(BaseModel):
    email: ClaimRequirementStateView
    firstName: ClaimRequirementStateView
    lastName: ClaimRequirementStateView
    staticAvatar: ClaimRequirementStateView
    animatedAvatar: ClaimRequirementStateView


class RefreshRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refreshToken: str


class RefreshResponse(BaseModel):
    claims: ClaimsStateView
    accessToken: str = Field(
        ..., description="Newly issued short-lived access token JWT."
    )
    refreshToken: str = Field(
        ...,
        description="Newly issued refresh token JWT; the presented token has been consumed.",
    )


class IntrospectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accessToken: str


class Status1(StrEnum):
    active = "active"
    revoked = "revoked"
    expired = "expired"
    not_found = "not_found"


class IntrospectResponse(BaseModel):
    status: Status1
    recommendedRecheckSeconds: int


class LogoutRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refreshToken: str


class LogoutResponse(BaseModel):
    revoked: bool


class RevokeAllRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject: str = Field(
        ...,
        description="Application-visible sector subject (`sub`) for the account to revoke.",
    )


class Revoked(Enum):
    """
    Authority-safe acknowledgement of the revocation request.
    """

    boolean_True = True


class RevokeAllResponse(BaseModel):
    revoked: Revoked = Field(
        ..., description="Authority-safe acknowledgement of the revocation request."
    )
    cleanupRowCount: int = Field(
        ...,
        description="Number of currently enumerated refresh-token rows suspended as best-effort cleanup.",
        ge=0,
    )


class Error(BaseModel):
    """
    Error response body. A missing, malformed, or structurally invalid JSON
    request body returns `InvalidBody` without parser or
    validation-library detail. A documented status-only private failure has
    an empty response body instead.

    """

    reason: str
    message: str | None = None
