# generated by datamodel-codegen:
#   filename:  session.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    ready: bool
    service: str
    version: str


class Requirement(StrEnum):
    SYNTHETIC_ONLY = "SYNTHETIC_ONLY"
    OFF = "OFF"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    SYNTHETIC_FALLBACK = "SYNTHETIC_FALLBACK"


class State(StrEnum):
    UNKNOWN = "UNKNOWN"
    GRANTED = "GRANTED"
    DENIED = "DENIED"


class ClaimRequirementStateView(BaseModel):
    requirement: Requirement
    state: State


class ClaimsStateView(BaseModel):
    email: ClaimRequirementStateView
    firstName: ClaimRequirementStateView
    lastName: ClaimRequirementStateView
    avatar: ClaimRequirementStateView


class RefreshRequest(BaseModel):
    refreshToken: str


class RefreshResponse(BaseModel):
    claims: ClaimsStateView
    accessToken: str = Field(
        ..., description="Newly issued short-lived access token JWT."
    )
    refreshToken: str = Field(
        ...,
        description="Newly issued refresh token JWT; the presented token has been consumed.",
    )


class IntrospectRequest(BaseModel):
    accessToken: str


class Status(StrEnum):
    active = "active"
    revoked = "revoked"
    expired = "expired"
    not_found = "not_found"


class IntrospectResponse(BaseModel):
    status: Status
    recommendedRecheckSeconds: int


class LogoutRequest(BaseModel):
    refreshToken: str


class LogoutResponse(BaseModel):
    revoked: bool


class RevokeAllRequest(BaseModel):
    subject: str = Field(
        ...,
        description="Application-visible sector subject (`sub`) for the account to revoke.",
    )


class RevokeAllResponse(BaseModel):
    revokedCount: int


class Error(BaseModel):
    reason: str
    message: str | None = None
