# generated by datamodel-codegen:
#   filename:  connect.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class EstablishRequest(BaseModel):
    applicationKey: str = Field(
        ..., description="Public key identifying the integrating application."
    )
    redirectUri: AnyUrl = Field(
        ..., description="URI the platform will redirect to after authentication."
    )
    state: str | None = Field(
        None,
        description="Opaque value echoed back in the redirect for CSRF protection.",
    )


class EstablishResponse(BaseModel):
    sessionId: str = Field(
        ..., description="Identifier for the established connect session."
    )
    authorizeUrl: AnyUrl = Field(
        ..., description="URL the end user should visit to complete authentication."
    )
    expiresAt: AwareDatetime | None = Field(
        None, description="When this session will expire if unused."
    )


class RedeemRequest(BaseModel):
    sessionId: str = Field(
        ..., description="Session identifier returned from /establish."
    )
    code: str = Field(
        ..., description="Authentication code obtained after the end user signs in."
    )


class RefreshRequest(BaseModel):
    refreshToken: str = Field(
        ..., description="Refresh token previously issued by /redeem or /refresh."
    )


class TokenType(StrEnum):
    """
    Token type; currently always "Bearer".
    """

    Bearer = "Bearer"


class TokenPair(BaseModel):
    accessToken: str = Field(
        ..., description="Short-lived application access token (JWT)."
    )
    refreshToken: str = Field(..., description="Long-lived refresh token.")
    expiresIn: int = Field(..., description="Lifetime of the access token in seconds.")
    tokenType: TokenType | None = Field(
        "Bearer", description='Token type; currently always "Bearer".'
    )


class Error(BaseModel):
    code: str = Field(..., description="Stable machine-readable error code.")
    message: str = Field(..., description="Human-readable error message.")
    requestId: str | None = Field(
        None, description="Identifier for correlating with platform logs."
    )
