# generated by datamodel-codegen:
#   filename:  connect.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Status(StrEnum):
    """
    The API invocation path completed successfully.
    """

    ok = "ok"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status = Field(
        ..., description="The API invocation path completed successfully."
    )
    service: str = Field(..., description="Stable runtime service identity.")
    version: str = Field(
        ..., description="Version from the deployed service's version manifest."
    )


class EstablishResponse(BaseModel):
    applicationAnchor: str
    exposureKey: str = Field(
        ...,
        description="Public half of the inquiry key pair; safe to share with the user agent.",
    )
    hiddenKey: str = Field(
        ...,
        description="Private half of the inquiry key pair; must stay on the originating client.",
    )


class StatusPollRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    exposureKey: str
    hiddenKey: str


class Status1(StrEnum):
    PENDING = "PENDING"


class StatusPollPendingResponse(BaseModel):
    status: Literal["PENDING"]


class Status2(StrEnum):
    REALIZED = "REALIZED"


class StatusPollRealizedResponse(BaseModel):
    status: Literal["REALIZED"]
    confirmationKey: str = Field(
        ...,
        description="One-time key proving the inquiry has been realized; pass to /redeem.",
    )


class RedeemRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    exposureKey: str
    hiddenKey: str
    confirmationKey: str


class Requirement(StrEnum):
    """
    The developer's policy for the claim. `SYNTHETIC_ONLY` always
    emits the generated placeholder and never asks for real data.
    `SYNTHETIC_FALLBACK` guarantees the claim is present but uses a
    generated placeholder (a stand-in name, a proxy email, or a
    generated avatar) when the user has not shared real data. Unlike `REQUIRED`, neither
    synthetic mode blocks issuance or raises an errand.

    """

    SYNTHETIC_ONLY = "SYNTHETIC_ONLY"
    OFF = "OFF"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    SYNTHETIC_FALLBACK = "SYNTHETIC_FALLBACK"


class State(StrEnum):
    UNKNOWN = "UNKNOWN"
    GRANTED = "GRANTED"
    DENIED = "DENIED"


class ClaimRequirementStateView(BaseModel):
    """
    One shareable claim: what the application requests (`requirement`)
    joined with the user's standing decision (`state`). `UNKNOWN` means
    the user was never asked; `DENIED` means the user explicitly
    declined.

    """

    requirement: Requirement = Field(
        ...,
        description="The developer's policy for the claim. `SYNTHETIC_ONLY` always\nemits the generated placeholder and never asks for real data.\n`SYNTHETIC_FALLBACK` guarantees the claim is present but uses a\ngenerated placeholder (a stand-in name, a proxy email, or a\ngenerated avatar) when the user has not shared real data. Unlike `REQUIRED`, neither\nsynthetic mode blocks issuance or raises an errand.\n",
    )
    state: State


class ClaimsStateView(BaseModel):
    """
    Per-claim view across the five shareable claims — why a claim is
    or is not present in the minted token (policy OFF, never asked,
    declined, or granted).

    """

    email: ClaimRequirementStateView
    firstName: ClaimRequirementStateView
    lastName: ClaimRequirementStateView
    staticAvatar: ClaimRequirementStateView
    animatedAvatar: ClaimRequirementStateView


class RedeemResponse(BaseModel):
    claims: ClaimsStateView
    applicationAnchor: str
    refreshToken: str = Field(
        ...,
        description="Long-lived refresh token (JWT). Decode its body to\n`RefreshTokenBody` (see schema). The refresh token leaves the\nsystem, so its body carries the sector `subject`, never the\nunderlying account identifier.\n",
    )
    accessToken: str = Field(
        ...,
        description="Short-lived access token (JWT). Decode its body to\n`AccessTokenBody` (see schema) — the application-visible user\nkey is the `subject` (sector subject) claim.\n",
    )


class AccessTokenBody(BaseModel):
    """
    Decoded body (payload) of a Sudomimus access token. The standard
    JWT envelope claims (`iss`, `aud`, `iat`, `exp`, `jti`, `kty`,
    `sub`) live in the JWT *header*; this object is the body. The
    application keys its users on `subject`. The `firstName`,
    `lastName`, `emailAddress`, `staticAvatarUrl`, and `animatedAvatarUrl` claims are consent-gated (claim
    sharing): each is minted only when the application's claim policy
    permits it AND the user has granted that claim, so any of them may
    be absent. Synthetic modes are the exception: `SYNTHETIC_ONLY` always
    emits a generated placeholder, and `SYNTHETIC_FALLBACK` emits real
    data when granted or the placeholder otherwise.

    """

    subject: str = Field(
        ...,
        description="The application-visible user identifier — the per-(account,\nsector) **sector subject**, also the OIDC `sub`. This is the\nvalue an application keys its users on; the underlying account\nidentifier never appears in a token. User-rotatable.\nOpaque: never parse or format-validate it.\n",
    )
    firstName: str | None = Field(
        None,
        description="Given name. Minted only when the application's claim policy\npermits it AND the user has granted the claim; may be absent\neven when the account has a value stored. Under a synthetic policy\nit is always present, possibly a placeholder name.\n",
    )
    lastName: str | None = Field(
        None, description="Family name. Same consent gating as `firstName`.\n"
    )
    emailAddress: str | None = Field(
        None,
        description="Email associated with this login. Consent-gated like\n`firstName` / `lastName` / avatar URLs (minted only when policy permits AND\nthe user granted the EMAIL claim). When a real value is included:\nthe exact email typed for email-OTP logins, otherwise the\naccount's primary email; omitted for accounts with no verified\nemail (e.g. Steam-only or AccessKey-only). Synthetic email policies\nare the exception: the field is then always present — a real\nverified email only under `SYNTHETIC_FALLBACK` when shared,\notherwise a `…@proxy.sudomimus.email` proxy address (best-effort\nforwarding, not guaranteed; not a verified mailbox).\n",
    )
    staticAvatarUrl: AnyUrl | None = Field(
        None,
        description="Sector-scoped static public avatar URL. Consent-gated like the other\nshareable claims and minted as `STATIC_AVATAR` when policy and grant\nallow it. The URL is pairwise to this account / sector delivery\nhandle, even when it resolves to the user's global avatar image.\nSynthetic avatar policies return a generated sector placeholder image.\n",
    )
    animatedAvatarUrl: AnyUrl | None = Field(
        None,
        description="Sector-scoped animated public avatar URL. Consent-gated separately\nfrom `staticAvatarUrl` and minted as `ANIMATED_AVATAR` when policy\nand grant allow it. If the selected avatar has no animation, this\nfield is the same URL as `staticAvatarUrl`.\n",
    )


class RefreshTokenBody(BaseModel):
    """
    Decoded body (payload) of a Sudomimus refresh token. Carries the
    sector `subject` (the same pairwise identifier as the access-token
    body) because the refresh token leaves the system and must never
    expose the underlying account identifier. Informational only —
    `/refresh` resolves the token by its `jti`, not by reading the body.

    """

    subject: str = Field(
        ...,
        description="The application-visible **sector subject**. Opaque: never\nparse or format-validate it.\n",
    )


class InfoRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applicationAnchor: str
    locale: str = Field(
        ...,
        description='IETF BCP 47 locale tag (e.g. "en-US"). Falls back to the application\'s default locale if not available.',
    )


class InfoResponse(BaseModel):
    applicationAnchor: str
    applicationName: str = Field(..., description="Localized application display name.")


class AuthenticationRuleConstraintCommon(BaseModel):
    accessTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for access token lifetime. Resolved at realize time.",
        ge=60,
        le=604800,
    )
    refreshTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for refresh token lifetime. Resolved at realize time.",
        ge=86400,
        le=31536000,
    )


class Method(StrEnum):
    PASSKEY_USERNAMELESS = "PASSKEY_USERNAMELESS"


class Method1(StrEnum):
    PASSKEY_REASONED = "PASSKEY_REASONED"


class Method2(StrEnum):
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"


class Method3(StrEnum):
    STEAM_TICKET = "STEAM_TICKET"


class Method4(StrEnum):
    STEAM_OPENID = "STEAM_OPENID"


class Method5(StrEnum):
    ACCESS_KEY_DIRECT = "ACCESS_KEY_DIRECT"


class Method6(StrEnum):
    GOOGLE_OAUTH = "GOOGLE_OAUTH"


class Method7(StrEnum):
    GITHUB_OAUTH = "GITHUB_OAUTH"


class Method8(StrEnum):
    DISCORD_OAUTH = "DISCORD_OAUTH"


class Method9(StrEnum):
    BATTLENET_OAUTH = "BATTLENET_OAUTH"


class Method10(StrEnum):
    X_OAUTH = "X_OAUTH"


class Method11(StrEnum):
    ENTERPRISE_FEDERATION_APPLICATION_MANAGED = (
        "ENTERPRISE_FEDERATION_APPLICATION_MANAGED"
    )


class Method12(StrEnum):
    ENTERPRISE_FEDERATION_DOMAIN_MANAGED = "ENTERPRISE_FEDERATION_DOMAIN_MANAGED"


class AuthenticationRulePasskeyUsernamelessPayload(BaseModel):
    """
    Empty payload — narrows to usernameless (discoverable-credential)
    passkey login, the "Sign in with a passkey" entry shown before any
    email is entered. Realize authorization is still decided by Layer 2.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRulePasskeyReasonedPayload(BaseModel):
    """
    Empty payload — narrows to email-first ("reasoned") passkey login,
    the passkey option offered after the user enters their email.
    Realize authorization is still decided by Layer 2.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleEmailVerificationPayload(BaseModel):
    """
    Empty payload — email-verification constraints carry no further parameters.
    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AllowedSteamAppId(RootModel[int]):
    root: int = Field(..., ge=1)


class AuthenticationRuleSteamTicketPayload(BaseModel):
    """
    Steam-native-ticket payload. Gates native-api's
    `/direct-issue/steam-ticket` flow. `allowedSteamAppIds` is the
    non-empty list of Steam App IDs whose tickets are accepted.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allowedSteamAppIds: list[AllowedSteamAppId] = Field(
        ..., max_length=128, min_length=1
    )


class AuthenticationRuleSteamOpenIdPayload(BaseModel):
    """
    Steam OpenID 2.0 carries no app-id concept (that is
    native-ticket-specific). Any Steam account is accepted as long
    as the application's rule set allows STEAM_OPENID at all.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleAccessKeyDirectPayload(BaseModel):
    """
    Gates native-api's `/direct-issue/access-key` flow. Credentials
    live in the dedicated `AccessKeyCredential` table; no row of
    this method ever appears in the `Authentication` table.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AllowedHostedDomain(RootModel[str]):
    root: str = Field(..., max_length=2048, min_length=1)


class AuthenticationRuleGoogleOAuthPayload(BaseModel):
    """
    Empty `allowedHostedDomains` means no hosted-domain gating. A
    non-empty list requires an exact, case-insensitive match against the
    Google Workspace `hd` claim. The server lowercases and deduplicates
    entries before persistence.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allowedHostedDomains: list[AllowedHostedDomain] | None = Field(None, max_length=128)


class AllowedGitHubOrg(RootModel[str]):
    root: str = Field(..., max_length=2048, min_length=1)


class AuthenticationRuleGitHubOAuthPayload(BaseModel):
    """
    Empty `allowedGitHubOrgs` array means no org gating — any
    GitHub account is accepted. Non-empty means the user must be a
    member of at least one listed organization (case-insensitive
    match on the org `login`). The `read:org` OAuth scope is only
    requested when at least one matching rule carries a non-empty
    allowlist; applications without org gating keep the minimal
    `read:user user:email` consent screen.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allowedGitHubOrgs: list[AllowedGitHubOrg] = Field(..., max_length=128)


class AllowedDiscordGuild(RootModel[str]):
    root: str = Field(..., max_length=2048, min_length=1)


class AuthenticationRuleDiscordOAuthPayload(BaseModel):
    """
    Empty `allowedDiscordGuilds` means no guild gating. A non-empty list
    requires membership in at least one listed Discord guild and causes
    the authentication flow to request the `guilds` scope. Entries are
    trimmed and deduplicated before persistence.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allowedDiscordGuilds: list[AllowedDiscordGuild] | None = Field(None, max_length=128)


class AuthenticationRuleBattleNetOAuthPayload(BaseModel):
    """
    Battle.net (Blizzard) has no per-application gating concept, so any
    Battle.net account is accepted as long as the application's rule set
    allows BATTLENET_OAUTH at all. Empty payload. Battle.net is an
    email-less provider, so Layer-2 EMAIL rules fail closed against a
    Battle.net-only account.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleXOAuthPayload(BaseModel):
    """
    X (formerly Twitter) has no per-application gating concept, so any
    X account is accepted as long as the application's rule set allows
    X_OAUTH at all. Empty payload. X is an email-less provider, so
    Layer-2 EMAIL rules fail closed against an X-only account.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleEnterpriseFederationApplicationManagedPayload(BaseModel):
    """
    Application-managed enterprise federation. `connectorAnchor` names an
    enabled FederationConnector owned by the application's organization.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    connectorAnchor: str = Field(..., max_length=2048, min_length=1, pattern="\\S")


class AuthenticationRuleEnterpriseFederationDomainManagedPayload(BaseModel):
    """
    Empty payload — the connector is selected from the verified adopted
    domain's SSO_ONLY policy rather than by the application.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class RealizeRuleConstraintCommon(BaseModel):
    accessTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for access token lifetime. Resolved at realize time.",
        ge=60,
        le=604800,
    )
    refreshTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for refresh token lifetime. Resolved at realize time.",
        ge=86400,
        le=31536000,
    )


class ConstraintType(StrEnum):
    EMAIL = "EMAIL"


class ConstraintType1(StrEnum):
    STEAM_ID = "STEAM_ID"


class ConstraintType2(StrEnum):
    ACCOUNT_ALIAS = "ACCOUNT_ALIAS"


class ConstraintType3(StrEnum):
    SECTOR_SUBJECT = "SECTOR_SUBJECT"


class ConstraintType4(StrEnum):
    EVERYONE = "EVERYONE"


class AllowedEmail(RootModel[str]):
    root: str = Field(..., max_length=254)


class RealizeRuleEmailPayload(BaseModel):
    allowedEmails: list[AllowedEmail] = Field(
        ...,
        description="List of email addresses or glob patterns the realized identity\nmust match. Glob patterns are bounded by server-side limits to\nprevent regex backtracking attacks.\n",
        max_length=128,
        min_length=1,
    )


class AllowedSteamId(RootModel[str]):
    root: str = Field(..., pattern="^(\\*|[0-9]{1,20})$")


class RealizeRuleSteamIdPayload(BaseModel):
    """
    Per-realize-time check against the realized account's SteamID64.
    Each entry is either the literal `"*"` (wildcard, allow any
    Steam identity) or a decimal SteamID64 string.

    """

    allowedSteamIds: list[AllowedSteamId] = Field(..., max_length=128, min_length=1)


class AllowedAccountAliase(RootModel[str]):
    root: str = Field(..., max_length=128, min_length=1)


class RealizeRuleAccountAliasPayload(BaseModel):
    """
    Exact match on the realizing account's **account alias** — the
    user-visible, application-invisible, rotatable handle the user
    reads in the With portal and shares out-of-band with whoever
    configures the rule. No wildcard — because the account does not
    yet exist during fresh registration, this constraint matches
    nothing for new sign-ups. The alias is opaque: it is compared by
    exact-string equality and never parsed or format-validated.

    """

    allowedAccountAliases: list[AllowedAccountAliase] = Field(
        ..., max_length=128, min_length=1
    )


class AllowedSectorSubject(RootModel[str]):
    root: str = Field(..., max_length=128, min_length=1)


class RealizeRuleSectorSubjectPayload(BaseModel):
    """
    Exact match on the realizing account's **sector subject** for the
    realizing application's sector — the application-visible token
    `sub` the owner already sees in their own logs. No wildcard.
    Rotating the subject locks the user out (it becomes a brand-new,
    not-yet-allow-listed identity) rather than letting them bypass the
    rule. The subject is opaque: compared by exact-string equality and
    never parsed or format-validated.

    """

    allowedSectorSubjects: list[AllowedSectorSubject] = Field(
        ..., max_length=128, min_length=1
    )


class RealizeRuleEveryonePayload(BaseModel):
    """
    Empty payload — the explicit EVERYONE constraint admits any realized
    identity on this side of the Layer-2 AND boundary.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class Type(StrEnum):
    CALLBACK = "CALLBACK"


class Payload(BaseModel):
    callbackUrl: str = Field(
        ...,
        description="Concrete callback URL for this inquiry. The host MUST match\none of the application's allowed callback domains. The scheme\nMUST be HTTPS except loopback HTTP for local development\n(`localhost`, `127.0.0.1`, `[::1]`). After realization,\nConnect appends the canonical `exposure-key` and\n`confirmation-key` query parameters. Existing query parameters\nand fragments are preserved; caller-supplied or duplicate\nvalues for the two canonical names are overwritten. The URL\nMUST be concrete and MUST NOT contain Inquiry-key templates.\nThe server enforces the length limit in UTF-8 bytes.\n",
        max_length=2048,
    )


class ReturnMethodCallback(BaseModel):
    type: Literal["CALLBACK"]
    payload: Payload


class Type1(StrEnum):
    STATUS_POLL = "STATUS_POLL"


class ReturnMethodStatusPoll(BaseModel):
    type: Literal["STATUS_POLL"]
    payload: dict[str, Any] = Field(
        ...,
        description="Empty payload — STATUS_POLL carries no per-inquiry parameters.",
    )


class Type2(StrEnum):
    REVEAL = "REVEAL"


class ReturnMethodReveal(BaseModel):
    type: Literal["REVEAL"]
    payload: dict[str, Any] = Field(
        ...,
        description="Empty payload. Tokens are surfaced directly in the UI at\nrealize time and the inquiry is marked redeemed immediately;\nany subsequent `/redeem` for the same inquiry fails with\n`InquiryAlreadyRedeemed`.\n",
    )


class Error(BaseModel):
    """
    Error response body. The Connect service emits `{ "reason": "<SymbolDescription>" }`
    for known failure modes. When the reason symbol's description begins with
    `PRIVATE`, the body is empty (zero bytes) and only the HTTP status carries
    signal — both `reason` and the body itself are absent in that case. A
    missing, malformed, or structurally invalid JSON request body returns
    `InvalidBody` without parser or validation-library detail.

    """

    reason: str | None = Field(None, description="Stable machine-readable reason code.")


class StatusPollResponse(
    RootModel[StatusPollPendingResponse | StatusPollRealizedResponse]
):
    root: StatusPollPendingResponse | StatusPollRealizedResponse = Field(
        ..., discriminator="status"
    )


class AuthenticationRuleConstraintPasskeyUsernameless(
    AuthenticationRuleConstraintCommon
):
    method: Literal["PASSKEY_USERNAMELESS"]
    payload: AuthenticationRulePasskeyUsernamelessPayload


class AuthenticationRuleConstraintPasskeyReasoned(AuthenticationRuleConstraintCommon):
    method: Literal["PASSKEY_REASONED"]
    payload: AuthenticationRulePasskeyReasonedPayload


class AuthenticationRuleConstraintEmailVerification(AuthenticationRuleConstraintCommon):
    method: Literal["EMAIL_VERIFICATION"]
    payload: AuthenticationRuleEmailVerificationPayload


class AuthenticationRuleConstraintSteamTicket(AuthenticationRuleConstraintCommon):
    method: Literal["STEAM_TICKET"]
    payload: AuthenticationRuleSteamTicketPayload


class AuthenticationRuleConstraintSteamOpenId(AuthenticationRuleConstraintCommon):
    method: Literal["STEAM_OPENID"]
    payload: AuthenticationRuleSteamOpenIdPayload


class AuthenticationRuleConstraintAccessKeyDirect(AuthenticationRuleConstraintCommon):
    method: Literal["ACCESS_KEY_DIRECT"]
    payload: AuthenticationRuleAccessKeyDirectPayload


class AuthenticationRuleConstraintGoogleOAuth(AuthenticationRuleConstraintCommon):
    method: Literal["GOOGLE_OAUTH"]
    payload: AuthenticationRuleGoogleOAuthPayload


class AuthenticationRuleConstraintGitHubOAuth(AuthenticationRuleConstraintCommon):
    method: Literal["GITHUB_OAUTH"]
    payload: AuthenticationRuleGitHubOAuthPayload


class AuthenticationRuleConstraintDiscordOAuth(AuthenticationRuleConstraintCommon):
    method: Literal["DISCORD_OAUTH"]
    payload: AuthenticationRuleDiscordOAuthPayload


class AuthenticationRuleConstraintBattleNetOAuth(AuthenticationRuleConstraintCommon):
    method: Literal["BATTLENET_OAUTH"]
    payload: AuthenticationRuleBattleNetOAuthPayload


class AuthenticationRuleConstraintXOAuth(AuthenticationRuleConstraintCommon):
    method: Literal["X_OAUTH"]
    payload: AuthenticationRuleXOAuthPayload


class AuthenticationRuleConstraintEnterpriseFederationApplicationManaged(
    AuthenticationRuleConstraintCommon
):
    method: Literal["ENTERPRISE_FEDERATION_APPLICATION_MANAGED"]
    payload: AuthenticationRuleEnterpriseFederationApplicationManagedPayload


class AuthenticationRuleConstraintEnterpriseFederationDomainManaged(
    AuthenticationRuleConstraintCommon
):
    method: Literal["ENTERPRISE_FEDERATION_DOMAIN_MANAGED"]
    payload: AuthenticationRuleEnterpriseFederationDomainManagedPayload


class RealizeRuleConstraintEmail(RealizeRuleConstraintCommon):
    constraintType: Literal["EMAIL"]
    payload: RealizeRuleEmailPayload


class RealizeRuleConstraintSteamId(RealizeRuleConstraintCommon):
    constraintType: Literal["STEAM_ID"]
    payload: RealizeRuleSteamIdPayload


class RealizeRuleConstraintAccountAlias(RealizeRuleConstraintCommon):
    constraintType: Literal["ACCOUNT_ALIAS"]
    payload: RealizeRuleAccountAliasPayload


class RealizeRuleConstraintSectorSubject(RealizeRuleConstraintCommon):
    constraintType: Literal["SECTOR_SUBJECT"]
    payload: RealizeRuleSectorSubjectPayload


class RealizeRuleConstraintEveryone(RealizeRuleConstraintCommon):
    constraintType: Literal["EVERYONE"]
    payload: RealizeRuleEveryonePayload


class ReturnMethodDeclaration(
    RootModel[ReturnMethodCallback | ReturnMethodStatusPoll | ReturnMethodReveal]
):
    root: ReturnMethodCallback | ReturnMethodStatusPoll | ReturnMethodReveal = Field(
        ..., discriminator="type"
    )


class AuthenticationRuleConstraint(
    RootModel[
        AuthenticationRuleConstraintPasskeyUsernameless
        | AuthenticationRuleConstraintPasskeyReasoned
        | AuthenticationRuleConstraintEmailVerification
        | AuthenticationRuleConstraintSteamTicket
        | AuthenticationRuleConstraintSteamOpenId
        | AuthenticationRuleConstraintAccessKeyDirect
        | AuthenticationRuleConstraintGoogleOAuth
        | AuthenticationRuleConstraintGitHubOAuth
        | AuthenticationRuleConstraintDiscordOAuth
        | AuthenticationRuleConstraintBattleNetOAuth
        | AuthenticationRuleConstraintXOAuth
        | AuthenticationRuleConstraintEnterpriseFederationApplicationManaged
        | AuthenticationRuleConstraintEnterpriseFederationDomainManaged
    ]
):
    root: (
        AuthenticationRuleConstraintPasskeyUsernameless
        | AuthenticationRuleConstraintPasskeyReasoned
        | AuthenticationRuleConstraintEmailVerification
        | AuthenticationRuleConstraintSteamTicket
        | AuthenticationRuleConstraintSteamOpenId
        | AuthenticationRuleConstraintAccessKeyDirect
        | AuthenticationRuleConstraintGoogleOAuth
        | AuthenticationRuleConstraintGitHubOAuth
        | AuthenticationRuleConstraintDiscordOAuth
        | AuthenticationRuleConstraintBattleNetOAuth
        | AuthenticationRuleConstraintXOAuth
        | AuthenticationRuleConstraintEnterpriseFederationApplicationManaged
        | AuthenticationRuleConstraintEnterpriseFederationDomainManaged
    ) = Field(..., discriminator="method")


class RealizeRuleConstraint(
    RootModel[
        RealizeRuleConstraintEmail
        | RealizeRuleConstraintSteamId
        | RealizeRuleConstraintAccountAlias
        | RealizeRuleConstraintSectorSubject
        | RealizeRuleConstraintEveryone
    ]
):
    root: (
        RealizeRuleConstraintEmail
        | RealizeRuleConstraintSteamId
        | RealizeRuleConstraintAccountAlias
        | RealizeRuleConstraintSectorSubject
        | RealizeRuleConstraintEveryone
    ) = Field(..., discriminator="constraintType")


class EstablishRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applicationAnchor: str = Field(
        ..., description="Public anchor identifying the integrating application."
    )
    authenticationConstraints: list[AuthenticationRuleConstraint] | None = Field(
        None,
        description="Optional per-inquiry narrowing of the application's\nauthentication-rule layer. Absent means no narrowing. If present,\nthe array MUST be non-empty; empty arrays are rejected with 400.\n",
        max_length=16,
        min_length=1,
    )
    realizeConstraints: list[RealizeRuleConstraint] | None = Field(
        None,
        description="Optional per-inquiry narrowing of the application's realize-rule\nlayer. Absent means no narrowing. If present, the array MUST be\nnon-empty; empty arrays are rejected with 400.\n",
        max_length=16,
        min_length=1,
    )
    returnMethods: list[ReturnMethodDeclaration] | None = Field(
        None,
        description="Optional per-inquiry return-method declaration. Connect accepts\nCALLBACK, STATUS_POLL, and REVEAL here; DIRECT_ISSUE, OIDC, and\nDEVICE_CODE are opened by their dedicated APIs after application-\nlevel ReturnRules are configured. CALLBACK doubles as the concrete\ndelivery info (carries the callback URL). Absent means no per-\ninquiry narrowing (CALLBACK is unreachable for this inquiry\nbecause no URL is anchored). If present, the array MUST be non-\nempty; empty arrays are rejected with 400.\n",
        max_length=3,
        min_length=1,
    )
