# generated by datamodel-codegen:
#   filename:  connect.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class HealthResponse(BaseModel):
    ready: bool
    service: str
    version: str


class EstablishResponse(BaseModel):
    applicationAnchor: str
    exposureKey: str = Field(
        ...,
        description="Public half of the inquiry key pair; safe to share with the user agent.",
    )
    hiddenKey: str = Field(
        ...,
        description="Private half of the inquiry key pair; must stay on the originating client.",
    )


class StatusPollRequest(BaseModel):
    exposureKey: str
    hiddenKey: str


class Status(StrEnum):
    PENDING = "PENDING"


class StatusPollPendingResponse(BaseModel):
    status: Literal["PENDING"]


class Status1(StrEnum):
    REALIZED = "REALIZED"


class StatusPollRealizedResponse(BaseModel):
    status: Literal["REALIZED"]
    confirmationKey: str = Field(
        ...,
        description="One-time key proving the inquiry has been realized; pass to /redeem.",
    )


class RedeemRequest(BaseModel):
    exposureKey: str
    hiddenKey: str
    confirmationKey: str


class RedeemResponse(BaseModel):
    applicationAnchor: str
    refreshToken: str = Field(
        ...,
        description="Long-lived refresh token (JWT). Decode its body to\n`RefreshTokenBody` (see schema). The refresh token leaves the\nsystem, so its body carries the sector `subject`, never the\ninternal account identifier.\n",
    )
    accessToken: str = Field(
        ...,
        description="Short-lived access token (JWT). Decode its body to\n`AccessTokenBody` (see schema) — the application-visible user\nkey is the `subject` (sector subject) claim.\n",
    )


class RefreshRequest(BaseModel):
    refreshToken: str


class RefreshResponse(BaseModel):
    accessToken: str = Field(
        ...,
        description="Short-lived access token (JWT). Decode its body to\n`AccessTokenBody` (see schema) — the application-visible user\nkey is the `subject` (sector subject) claim.\n",
    )
    refreshToken: str = Field(
        ...,
        description="Newly issued refresh token (JWT); body is `RefreshTokenBody`.\nThe presented refresh token is invalidated atomically as part\nof the same call; re-presenting it is treated as compromise\nunder OAuth 2.1 BCP §4.14.2 strict rotation.\n",
    )


class AccessTokenBody(BaseModel):
    """
    Decoded body (payload) of a Sudomimus access token. The standard
    JWT envelope claims (`iss`, `aud`, `iat`, `exp`, `jti`, `kty`,
    `sub`) live in the JWT *header*; this object is the body. The
    application keys its users on `subject`. The `firstName`,
    `lastName`, and `emailAddress` claims are consent-gated (claim
    sharing): each is minted only when the application's claim policy
    permits it AND the user has granted that claim, so any of them may
    be absent.

    """

    subject: str = Field(
        ...,
        description="The application-visible user identifier — the per-(account,\nsector) **sector subject**, also the OIDC `sub`. This is the\nvalue an application keys its users on; the raw internal\naccount identifier never appears in a token. User-rotatable.\nOpaque: never parse or format-validate it.\n",
    )
    firstName: str | None = Field(
        None,
        description="Given name. Minted only when the application's claim policy\npermits it AND the user has granted the claim; may be absent\neven when the account has a value stored.\n",
    )
    lastName: str | None = Field(
        None, description="Family name. Same consent gating as `firstName`.\n"
    )
    emailAddress: str | None = Field(
        None,
        description="Verified email associated with this login. Consent-gated like\n`firstName` / `lastName` (minted only when policy permits AND\nthe user granted the EMAIL claim). When included: the exact\nemail typed for email-OTP logins, otherwise the account's\nprimary email. Always omitted for accounts with no verified\nemail (e.g. Steam-only or AccessKey-only).\n",
    )


class RefreshTokenBody(BaseModel):
    """
    Decoded body (payload) of a Sudomimus refresh token. Carries the
    sector `subject` (the same pairwise identifier as the access-token
    body) because the refresh token leaves the system and must never
    expose the internal account identifier. Informational only —
    `/refresh` resolves the token by its `jti`, not by reading the body.

    """

    subject: str = Field(
        ...,
        description="The application-visible **sector subject**. Opaque: never\nparse or format-validate it.\n",
    )


class InfoRequest(BaseModel):
    applicationAnchor: str
    locale: str = Field(
        ...,
        description='IETF BCP 47 locale tag (e.g. "en-US"). Falls back to the application\'s default locale if not available.',
    )


class InfoResponse(BaseModel):
    applicationAnchor: str
    applicationName: str = Field(..., description="Localized application display name.")
    applicationPublicKey: str = Field(
        ...,
        description="PEM-encoded application public key used to verify issued JWTs.",
    )


class IntrospectRequest(BaseModel):
    accessToken: str = Field(
        ...,
        description="A Sudomimus-issued access token (JWT). Its signature is verified; its own expiry is not enforced.",
    )


class Status2(StrEnum):
    """
    Revocation state of the session behind the access token. `not_found`
    covers an unknown session or one belonging to a different application.

    """

    active = "active"
    revoked = "revoked"
    expired = "expired"
    not_found = "not_found"


class IntrospectResponse(BaseModel):
    status: Status2 = Field(
        ...,
        description="Revocation state of the session behind the access token. `not_found`\ncovers an unknown session or one belonging to a different application.\n",
    )
    recommendedRecheckSeconds: int = Field(
        ...,
        description="Suggested minimum number of seconds to cache this result before re-checking.",
    )


class LogoutRequest(BaseModel):
    refreshToken: str = Field(
        ..., description="The refresh token (JWT) whose session should be revoked."
    )


class LogoutResponse(BaseModel):
    revoked: bool = Field(
        ...,
        description="True if the session is now revoked, including sessions that were already revoked or expired.",
    )


class RevokeAllRequest(BaseModel):
    subject: str = Field(
        ...,
        description="The sector subject the application sees for the user (the access / id token `sub`). Reverse-mapped server-side to the underlying account, whose sessions are then revoked for the calling application. A subject the application has never been issued (or one from another sector) revokes nothing.",
    )


class RevokeAllResponse(BaseModel):
    revokedCount: int = Field(
        ..., description="Number of refresh tokens that were revoked."
    )


class Method(StrEnum):
    """
    Which authentication method this constraint narrows to.
    """

    PASSKEY = "PASSKEY"
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
    STEAM_TICKET = "STEAM_TICKET"
    STEAM_OPENID = "STEAM_OPENID"
    ACCESS_KEY_DIRECT = "ACCESS_KEY_DIRECT"
    GOOGLE_OAUTH = "GOOGLE_OAUTH"
    GITHUB_OAUTH = "GITHUB_OAUTH"
    DISCORD_OAUTH = "DISCORD_OAUTH"
    BATTLENET_OAUTH = "BATTLENET_OAUTH"
    X_OAUTH = "X_OAUTH"


class AuthenticationRulePasskeyPayload(BaseModel):
    """
    Passkey-method payload. `allowUsernameless` opts the application
    in to discoverable-credential ("usernameless") passkey login,
    where the user authenticates without first entering an email.
    Absent or `false` keeps the email-first flow; only the entry
    path is affected — realize authorization is still decided
    entirely by Layer 2.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allowUsernameless: bool | None = None


class AuthenticationRuleEmailVerificationPayload(BaseModel):
    """
    Empty payload — email-verification constraints carry no further parameters.
    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AllowedSteamAppId(RootModel[int]):
    root: int = Field(..., ge=1)


class AuthenticationRuleSteamTicketPayload(BaseModel):
    """
    Steam-native-ticket payload. Gates native-api's
    `/direct-issue/steam-ticket` flow. `allowedSteamAppIds` is the
    non-empty list of Steam App IDs whose tickets are accepted.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allowedSteamAppIds: list[AllowedSteamAppId] = Field(..., min_length=1)


class AuthenticationRuleSteamOpenIdPayload(BaseModel):
    """
    Steam OpenID 2.0 carries no app-id concept (that is
    native-ticket-specific). Any Steam account is accepted as long
    as the application's rule set allows STEAM_OPENID at all.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleAccessKeyDirectPayload(BaseModel):
    """
    Gates native-api's `/direct-issue/access-key` flow. Credentials
    live in the dedicated `AccessKeyCredential` table; no row of
    this method ever appears in the `Authentication` table.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleGoogleOAuthPayload(BaseModel):
    """
    Phase 1: any Google account is accepted as long as the
    application's rule set allows GOOGLE_OAUTH at all. A later
    phase will add `allowedHostedDomains: string[]` for Google
    Workspace gating.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AllowedGitHubOrg(RootModel[str]):
    root: str = Field(..., min_length=1)


class AuthenticationRuleGitHubOAuthPayload(BaseModel):
    """
    Empty `allowedGitHubOrgs` array means no org gating — any
    GitHub account is accepted. Non-empty means the user must be a
    member of at least one listed organization (case-insensitive
    match on the org `login`). The `read:org` OAuth scope is only
    requested when at least one matching rule carries a non-empty
    allowlist; applications without org gating keep the minimal
    `read:user user:email` consent screen.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    allowedGitHubOrgs: list[AllowedGitHubOrg]


class AuthenticationRuleDiscordOAuthPayload(BaseModel):
    """
    Phase 1: any Discord account is accepted as long as the
    application's rule set allows DISCORD_OAUTH at all. Phase 1.5
    will add `allowedDiscordGuilds: string[]` for guild (server)
    gating, which will additionally request the `guilds` OAuth
    scope and fetch `GET /users/@me/guilds`.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleBattleNetOAuthPayload(BaseModel):
    """
    Battle.net (Blizzard) has no per-application gating concept, so any
    Battle.net account is accepted as long as the application's rule set
    allows BATTLENET_OAUTH at all. Empty payload. Battle.net is an
    email-less provider, so Layer-2 EMAIL rules fail closed against a
    Battle.net-only account.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class AuthenticationRuleXOAuthPayload(BaseModel):
    """
    X (formerly Twitter) has no per-application gating concept, so any
    X account is accepted as long as the application's rule set allows
    X_OAUTH at all. Empty payload. X is an email-less provider, so
    Layer-2 EMAIL rules fail closed against an X-only account.

    """

    model_config = ConfigDict(
        extra="forbid",
    )


class ConstraintType(StrEnum):
    """
    Which realize-rule kind this constraint narrows to.
    """

    EMAIL = "EMAIL"
    STEAM_ID = "STEAM_ID"
    ACCOUNT_ALIAS = "ACCOUNT_ALIAS"
    SECTOR_SUBJECT = "SECTOR_SUBJECT"


class RealizeRuleEmailPayload(BaseModel):
    allowedEmails: list[str] = Field(
        ...,
        description="List of email addresses or glob patterns the realized identity\nmust match. Glob patterns are bounded by server-side limits to\nprevent regex backtracking attacks.\n",
    )


class AllowedSteamId(RootModel[str]):
    root: str = Field(..., pattern="^(\\*|[0-9]{1,20})$")


class RealizeRuleSteamIdPayload(BaseModel):
    """
    Per-realize-time check against the realized account's SteamID64.
    Each entry is either the literal `"*"` (wildcard, allow any
    Steam identity) or a decimal SteamID64 string.

    """

    allowedSteamIds: list[AllowedSteamId]


class AllowedAccountAliase(RootModel[str]):
    root: str = Field(..., max_length=128, min_length=1)


class RealizeRuleAccountAliasPayload(BaseModel):
    """
    Exact match on the realizing account's **account alias** — the
    user-visible, application-invisible, rotatable handle the user
    reads in the With portal and shares out-of-band with whoever
    configures the rule. No wildcard — because the account does not
    yet exist during fresh registration, this constraint matches
    nothing for new sign-ups. The alias is opaque: it is compared by
    exact-string equality and never parsed or format-validated.

    """

    allowedAccountAliases: list[AllowedAccountAliase]


class AllowedSectorSubject(RootModel[str]):
    root: str = Field(..., max_length=128, min_length=1)


class RealizeRuleSectorSubjectPayload(BaseModel):
    """
    Exact match on the realizing account's **sector subject** for the
    realizing application's sector — the application-visible token
    `sub` the owner already sees in their own logs. No wildcard.
    Rotating the subject locks the user out (it becomes a brand-new,
    not-yet-allow-listed identity) rather than letting them bypass the
    rule. The subject is opaque: compared by exact-string equality and
    never parsed or format-validated.

    """

    allowedSectorSubjects: list[AllowedSectorSubject]


class Type(StrEnum):
    CALLBACK = "CALLBACK"


class Payload(BaseModel):
    callbackUrl: str = Field(
        ...,
        description="Concrete callback URL for this inquiry. The host MUST match\none of the application's allowed callback domains.\n",
    )


class ReturnMethodCallback(BaseModel):
    type: Literal["CALLBACK"]
    payload: Payload


class Type1(StrEnum):
    STATUS_POLL = "STATUS_POLL"


class ReturnMethodStatusPoll(BaseModel):
    type: Literal["STATUS_POLL"]
    payload: dict[str, Any] = Field(
        ...,
        description="Empty payload — STATUS_POLL carries no per-inquiry parameters.",
    )


class Type2(StrEnum):
    REVEAL = "REVEAL"


class ReturnMethodReveal(BaseModel):
    type: Literal["REVEAL"]
    payload: dict[str, Any] = Field(
        ...,
        description="Empty payload. Tokens are surfaced directly in the UI at\nrealize time and the inquiry is marked redeemed immediately;\nany subsequent `/redeem` for the same inquiry fails with\n`InquiryAlreadyRedeemed`.\n",
    )


class Type3(StrEnum):
    DIRECT_ISSUE = "DIRECT_ISSUE"


class ReturnMethodDirectIssue(BaseModel):
    type: Literal["DIRECT_ISSUE"]
    payload: dict[str, Any] = Field(
        ...,
        description="Empty payload. Opts the application in to native-api's\ndirect-issue flows (`/direct-issue/steam-ticket`,\n`/direct-issue/access-key`). Per-inquiry payload is empty\nbecause direct-issue does not flow through `/establish`.\n",
    )


class Type4(StrEnum):
    OIDC = "OIDC"


class ReturnMethodOidc(BaseModel):
    type: Literal["OIDC"]
    payload: dict[str, Any] = Field(
        ...,
        description="Accepted on the wire for symmetry, but in practice OIDC is\nnot declared per-inquiry — the OIDC API drives its own\ninquiry against Connect via CALLBACK-to-self. The matching\nper-inquiry payload is therefore empty.\n",
    )


class Error(BaseModel):
    """
    Error response body. The Connect service emits `{ "reason": "<SymbolDescription>" }`
    for known failure modes. When the reason symbol's description begins with
    `PRIVATE`, the body is empty (zero bytes) and only the HTTP status carries
    signal — both `reason` and the body itself are absent in that case.

    """

    reason: str | None = Field(None, description="Stable machine-readable reason code.")


class StatusPollResponse(
    RootModel[StatusPollPendingResponse | StatusPollRealizedResponse]
):
    root: StatusPollPendingResponse | StatusPollRealizedResponse = Field(
        ..., discriminator="status"
    )


class AuthenticationRuleConstraint(BaseModel):
    method: Method = Field(
        ..., description="Which authentication method this constraint narrows to."
    )
    payload: (
        AuthenticationRulePasskeyPayload
        | AuthenticationRuleEmailVerificationPayload
        | AuthenticationRuleSteamTicketPayload
        | AuthenticationRuleSteamOpenIdPayload
        | AuthenticationRuleAccessKeyDirectPayload
        | AuthenticationRuleGoogleOAuthPayload
        | AuthenticationRuleGitHubOAuthPayload
        | AuthenticationRuleDiscordOAuthPayload
        | AuthenticationRuleBattleNetOAuthPayload
        | AuthenticationRuleXOAuthPayload
    )
    accessTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for access token lifetime. Resolved at realize time.",
    )
    refreshTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for refresh token lifetime. Resolved at realize time.",
    )


class RealizeRuleConstraint(BaseModel):
    constraintType: ConstraintType = Field(
        ..., description="Which realize-rule kind this constraint narrows to."
    )
    payload: (
        RealizeRuleEmailPayload
        | RealizeRuleSteamIdPayload
        | RealizeRuleAccountAliasPayload
        | RealizeRuleSectorSubjectPayload
    )
    accessTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for access token lifetime. Resolved at realize time.",
    )
    refreshTokenTtlSeconds: int | None = Field(
        None,
        description="Per-constraint override for refresh token lifetime. Resolved at realize time.",
    )


class ReturnMethodDeclaration(
    RootModel[
        ReturnMethodCallback
        | ReturnMethodStatusPoll
        | ReturnMethodReveal
        | ReturnMethodDirectIssue
        | ReturnMethodOidc
    ]
):
    root: (
        ReturnMethodCallback
        | ReturnMethodStatusPoll
        | ReturnMethodReveal
        | ReturnMethodDirectIssue
        | ReturnMethodOidc
    ) = Field(..., discriminator="type")


class EstablishRequest(BaseModel):
    applicationAnchor: str = Field(
        ..., description="Public anchor identifying the integrating application."
    )
    authenticationConstraints: list[AuthenticationRuleConstraint] | None = Field(
        None,
        description="Optional per-inquiry narrowing of the application's\nauthentication-rule layer. Absent means no narrowing. If present,\nthe array MUST be non-empty; empty arrays are rejected with 400.\n",
    )
    realizeConstraints: list[RealizeRuleConstraint] | None = Field(
        None,
        description="Optional per-inquiry narrowing of the application's realize-rule\nlayer. Absent means no narrowing. If present, the array MUST be\nnon-empty; empty arrays are rejected with 400.\n",
    )
    returnMethods: list[ReturnMethodDeclaration] | None = Field(
        None,
        description="Optional per-inquiry return-method declaration. Doubles as the\nconcrete delivery info for CALLBACK (carries the callback URL).\nAbsent means no per-inquiry narrowing (CALLBACK is unreachable\nfor this inquiry because no URL is anchored). If present, the\narray MUST be non-empty; empty arrays are rejected with 400.\n",
    )
