/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Connect invocation health and deployment identity. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/establish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Establish a new authentication inquiry for an application.
         * @description Creates an authentication inquiry for the calling application. The
         *     client-auth JWT binds the exact request bytes and is single-use; see
         *     `SudomimusClientJWT` for its claim contract.
         *
         *     Constraint and return-method arrays are optional. When supplied, they
         *     narrow the application's configured rules and MUST be non-empty. The
         *     schemas define per-field limits; the three arrays together are limited
         *     to 65,536 serialized UTF-8 bytes.
         */
        post: operations["establish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status-poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll the realization status of an authentication inquiry. */
        post: operations["statusPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem a realized inquiry for an application token pair. */
        post: operations["redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch localized public metadata about an application. */
        post: operations["info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description The API invocation path completed successfully.
             * @enum {string}
             */
            status: "ok";
            /** @description Stable runtime service identity. */
            service: string;
            /** @description Version from the deployed service's version manifest. */
            version: string;
        };
        EstablishRequest: {
            /** @description Public anchor identifying the integrating application. */
            applicationAnchor: string;
            /**
             * @description Optional per-inquiry narrowing of the application's
             *     authentication-rule layer. Absent means no narrowing. If present,
             *     the array MUST be non-empty; empty arrays are rejected with 400.
             */
            authenticationConstraints?: components["schemas"]["AuthenticationRuleConstraint"][];
            /**
             * @description Optional per-inquiry narrowing of the application's realize-rule
             *     layer. Absent means no narrowing. If present, the array MUST be
             *     non-empty; empty arrays are rejected with 400.
             */
            realizeConstraints?: components["schemas"]["RealizeRuleConstraint"][];
            /**
             * @description Optional return methods for this inquiry. Connect accepts CALLBACK,
             *     STATUS_POLL, and REVEAL. CALLBACK includes its concrete delivery
             *     URL. Absence means no per-inquiry narrowing, but CALLBACK is not
             *     available without a URL. If supplied, the array MUST be non-empty.
             */
            returnMethods?: components["schemas"]["ReturnMethodDeclaration"][];
        };
        EstablishResponse: {
            applicationAnchor: string;
            /** @description Public half of the inquiry key pair; safe to share with the user agent. */
            exposureKey: string;
            /** @description Private half of the inquiry key pair; must stay on the originating client. */
            hiddenKey: string;
        };
        StatusPollRequest: {
            exposureKey: string;
            hiddenKey: string;
        };
        StatusPollResponse: components["schemas"]["StatusPollPendingResponse"] | components["schemas"]["StatusPollRealizedResponse"];
        StatusPollPendingResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "PENDING";
        };
        StatusPollRealizedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "REALIZED";
            /** @description One-time key proving the inquiry has been realized; pass to /redeem. */
            confirmationKey: string;
        };
        RedeemRequest: {
            exposureKey: string;
            hiddenKey: string;
            confirmationKey: string;
        };
        /**
         * @description One shareable claim: what the application requests (`requirement`)
         *     joined with the user's standing decision (`state`). `UNKNOWN` means
         *     the user was never asked; `DENIED` means the user explicitly
         *     declined.
         */
        ClaimRequirementStateView: {
            /**
             * @description The developer's policy for the claim. `SYNTHETIC_ONLY` always
             *     emits the generated placeholder and never asks for real data.
             *     `SYNTHETIC_FALLBACK` guarantees the claim is present but uses a
             *     generated placeholder (a stand-in name, a proxy email, or a
             *     generated avatar) when the user has not shared real data. Unlike `REQUIRED`, neither
             *     synthetic mode blocks issuance or raises an errand.
             * @enum {string}
             */
            requirement: "SYNTHETIC_ONLY" | "OFF" | "OPTIONAL" | "REQUIRED" | "SYNTHETIC_FALLBACK";
            /** @enum {string} */
            state: "UNKNOWN" | "GRANTED" | "DENIED";
        };
        /**
         * @description Per-claim view across the five shareable claims — why a claim is
         *     or is not present in the minted token (policy OFF, never asked,
         *     declined, or granted).
         */
        ClaimsStateView: {
            email: components["schemas"]["ClaimRequirementStateView"];
            firstName: components["schemas"]["ClaimRequirementStateView"];
            lastName: components["schemas"]["ClaimRequirementStateView"];
            staticAvatar: components["schemas"]["ClaimRequirementStateView"];
            animatedAvatar: components["schemas"]["ClaimRequirementStateView"];
        };
        RedeemResponse: {
            claims: components["schemas"]["ClaimsStateView"];
            applicationAnchor: string;
            /**
             * @description Long-lived refresh token (JWT). Decode its protected header as
             *     `RefreshTokenHeader` and its body as `RefreshTokenBody`. The
             *     payload binds the logical session as `sid`, names the rotating
             *     bearer instance as `jti`, and carries a positive
             *     `rotationVersion`. It carries no user identifier or profile data.
             */
            refreshToken: string;
            /**
             * @description Short-lived access token (JWT). Decode its protected header as
             *     `AccessTokenHeader` and its body as `AccessTokenBody`. The
             *     payload carries the application-visible user key as `sub`, the
             *     logical session as `sid`, and this access-token instance as `jti`.
             *     Fetch current shared profile data from Session API `/userinfo`.
             */
            accessToken: string;
        };
        /**
         * @description Exact JOSE protected header of a Sudomimus application access token.
         *     Registered JWT claims live in the payload.
         */
        AccessTokenHeader: {
            /** @enum {string} */
            alg: "RS256";
            /** @description Application token-signing key identifier. */
            kid: string;
            /** @enum {string} */
            typ: "vnd.sudomimus.application-access+jwt";
        };
        /**
         * @description Minimal payload of a Sudomimus access token. It contains only
         *     registered JWT claims and session binding. It never contains a raw
         *     account identifier or profile claims; use Session API `/userinfo` for
         *     current consent-gated identity data.
         */
        AccessTokenBody: {
            /** Format: uri */
            iss: string;
            /** @description Public application anchor. */
            aud: string;
            /** @description Pairwise sector subject; use this opaque value as the application-visible user key. */
            sub: string;
            /** @description Stable identifier of the logical ApplicationSession. */
            sid: string;
            /** @description Unique identifier of this access-token instance; distinct from `sid`. */
            jti: string;
            iat: number;
            exp: number;
        };
        /**
         * @description Exact JOSE protected header of a Sudomimus refresh token. Registered
         *     JWT claims and rotation state live in the payload.
         */
        RefreshTokenHeader: {
            /** @enum {string} */
            alg: "RS256";
            /** @description Application token-signing key identifier. */
            kid: string;
            /** @enum {string} */
            typ: "vnd.sudomimus.application-refresh+jwt";
        };
        /**
         * @description Minimal payload of a Sudomimus refresh token. `sid` stays stable across
         *     rotation, while every signed version has a distinct `jti` and positive
         *     `rotationVersion`. The payload contains no user identifier, profile
         *     claim, or raw account identifier.
         */
        RefreshTokenBody: {
            /** Format: uri */
            iss: string;
            /** @description Public application anchor. */
            aud: string;
            /** @description Stable identifier of the logical ApplicationSession. */
            sid: string;
            /** @description Identifier of this exact rotating refresh-token version. */
            jti: string;
            iat: number;
            exp: number;
            /**
             * @description Monotonic refresh version within `sid`. A successful rotation
             *     increments it by one; callers must store the newly returned token.
             */
            rotationVersion: number;
        };
        InfoRequest: {
            applicationAnchor: string;
            /** @description IETF BCP 47 locale tag (e.g. "en-US"). Falls back to the application's default locale if not available. */
            locale: string;
        };
        InfoResponse: {
            applicationAnchor: string;
            /** @description Localized application display name. */
            applicationName: string;
        };
        AuthenticationRuleConstraint: components["schemas"]["AuthenticationRuleConstraintPasskeyUsernameless"] | components["schemas"]["AuthenticationRuleConstraintPasskeyReasoned"] | components["schemas"]["AuthenticationRuleConstraintEmailVerification"] | components["schemas"]["AuthenticationRuleConstraintSteamTicket"] | components["schemas"]["AuthenticationRuleConstraintSteamOpenId"] | components["schemas"]["AuthenticationRuleConstraintAccessKeyDirect"] | components["schemas"]["AuthenticationRuleConstraintGoogleOAuth"] | components["schemas"]["AuthenticationRuleConstraintGitHubOAuth"] | components["schemas"]["AuthenticationRuleConstraintDiscordOAuth"] | components["schemas"]["AuthenticationRuleConstraintBattleNetOAuth"] | components["schemas"]["AuthenticationRuleConstraintXOAuth"] | components["schemas"]["AuthenticationRuleConstraintEnterpriseFederationApplicationManaged"] | components["schemas"]["AuthenticationRuleConstraintEnterpriseFederationDomainManaged"];
        AuthenticationRuleConstraintCommon: {
            /** @description Per-constraint override for access token lifetime. Resolved at realize time. */
            accessTokenTtlSeconds?: number;
            /** @description Per-constraint override for refresh token lifetime. Resolved at realize time. */
            refreshTokenTtlSeconds?: number;
        };
        AuthenticationRuleConstraintPasskeyUsernameless: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "PASSKEY_USERNAMELESS";
            payload: components["schemas"]["AuthenticationRulePasskeyUsernamelessPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "PASSKEY_USERNAMELESS";
        };
        AuthenticationRuleConstraintPasskeyReasoned: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "PASSKEY_REASONED";
            payload: components["schemas"]["AuthenticationRulePasskeyReasonedPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "PASSKEY_REASONED";
        };
        AuthenticationRuleConstraintEmailVerification: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "EMAIL_VERIFICATION";
            payload: components["schemas"]["AuthenticationRuleEmailVerificationPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "EMAIL_VERIFICATION";
        };
        AuthenticationRuleConstraintSteamTicket: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "STEAM_TICKET";
            payload: components["schemas"]["AuthenticationRuleSteamTicketPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "STEAM_TICKET";
        };
        AuthenticationRuleConstraintSteamOpenId: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "STEAM_OPENID";
            payload: components["schemas"]["AuthenticationRuleSteamOpenIdPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "STEAM_OPENID";
        };
        AuthenticationRuleConstraintAccessKeyDirect: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "ACCESS_KEY_DIRECT";
            payload: components["schemas"]["AuthenticationRuleAccessKeyDirectPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "ACCESS_KEY_DIRECT";
        };
        AuthenticationRuleConstraintGoogleOAuth: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "GOOGLE_OAUTH";
            payload: components["schemas"]["AuthenticationRuleGoogleOAuthPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "GOOGLE_OAUTH";
        };
        AuthenticationRuleConstraintGitHubOAuth: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "GITHUB_OAUTH";
            payload: components["schemas"]["AuthenticationRuleGitHubOAuthPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "GITHUB_OAUTH";
        };
        AuthenticationRuleConstraintDiscordOAuth: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "DISCORD_OAUTH";
            payload: components["schemas"]["AuthenticationRuleDiscordOAuthPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "DISCORD_OAUTH";
        };
        AuthenticationRuleConstraintBattleNetOAuth: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "BATTLENET_OAUTH";
            payload: components["schemas"]["AuthenticationRuleBattleNetOAuthPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "BATTLENET_OAUTH";
        };
        AuthenticationRuleConstraintXOAuth: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "X_OAUTH";
            payload: components["schemas"]["AuthenticationRuleXOAuthPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "X_OAUTH";
        };
        AuthenticationRuleConstraintEnterpriseFederationApplicationManaged: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "ENTERPRISE_FEDERATION_APPLICATION_MANAGED";
            payload: components["schemas"]["AuthenticationRuleEnterpriseFederationApplicationManagedPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "ENTERPRISE_FEDERATION_APPLICATION_MANAGED";
        };
        AuthenticationRuleConstraintEnterpriseFederationDomainManaged: components["schemas"]["AuthenticationRuleConstraintCommon"] & {
            /** @enum {string} */
            method: "ENTERPRISE_FEDERATION_DOMAIN_MANAGED";
            payload: components["schemas"]["AuthenticationRuleEnterpriseFederationDomainManagedPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "ENTERPRISE_FEDERATION_DOMAIN_MANAGED";
        };
        /**
         * @description Empty payload — narrows to usernameless (discoverable-credential)
         *     passkey login shown before an email is entered. Other configured
         *     authorization rules still apply.
         */
        AuthenticationRulePasskeyUsernamelessPayload: Record<string, never>;
        /**
         * @description Empty payload — narrows to email-first ("reasoned") passkey login,
         *     the passkey option offered after the user enters an email. Other
         *     configured authorization rules still apply.
         */
        AuthenticationRulePasskeyReasonedPayload: Record<string, never>;
        /** @description Empty payload — email-verification constraints carry no further parameters. */
        AuthenticationRuleEmailVerificationPayload: Record<string, never>;
        /**
         * @description Steam-native-ticket payload. Gates native-api's
         *     `/direct-issue/steam-ticket` flow. `allowedSteamAppIds` is the
         *     non-empty list of Steam App IDs whose tickets are accepted.
         */
        AuthenticationRuleSteamTicketPayload: {
            allowedSteamAppIds: number[];
        };
        /**
         * @description Steam OpenID 2.0 carries no app-id concept (that is
         *     native-ticket-specific). Any Steam account is accepted as long
         *     as the application's rule set allows STEAM_OPENID at all.
         */
        AuthenticationRuleSteamOpenIdPayload: Record<string, never>;
        /** @description Enables Native API `/direct-issue/access-key` authentication. */
        AuthenticationRuleAccessKeyDirectPayload: Record<string, never>;
        /**
         * @description Empty `allowedHostedDomains` means no hosted-domain gating. A
         *     non-empty list requires an exact, case-insensitive match against the
         *     Google Workspace `hd` claim. Matching is case-insensitive.
         */
        AuthenticationRuleGoogleOAuthPayload: {
            allowedHostedDomains?: string[];
        };
        /**
         * @description Empty `allowedGitHubOrgs` array means no org gating — any
         *     GitHub account is accepted. Non-empty means the user must be a
         *     member of at least one listed organization (case-insensitive
         *     match on the org `login`). The `read:org` OAuth scope is only
         *     requested when at least one matching rule carries a non-empty
         *     allowlist; applications without org gating keep the minimal
         *     `read:user user:email` consent screen.
         */
        AuthenticationRuleGitHubOAuthPayload: {
            allowedGitHubOrgs: string[];
        };
        /**
         * @description Empty `allowedDiscordGuilds` means no guild gating. A non-empty list
         *     requires membership in at least one listed Discord guild and causes
         *     the authentication flow to request the `guilds` scope.
         */
        AuthenticationRuleDiscordOAuthPayload: {
            allowedDiscordGuilds?: string[];
        };
        /**
         * @description Battle.net (Blizzard) has no per-application gating concept, so any
         *     Battle.net account is accepted as long as the application's rule set
         *     allows BATTLENET_OAUTH at all. Empty payload. Battle.net is an
         *     email-less provider, so Layer-2 EMAIL rules fail closed against a
         *     Battle.net-only account.
         */
        AuthenticationRuleBattleNetOAuthPayload: Record<string, never>;
        /**
         * @description X (formerly Twitter) has no per-application gating concept, so any
         *     X account is accepted as long as the application's rule set allows
         *     X_OAUTH at all. Empty payload. X is an email-less provider, so
         *     Layer-2 EMAIL rules fail closed against an X-only account.
         */
        AuthenticationRuleXOAuthPayload: Record<string, never>;
        /**
         * @description Application-managed enterprise federation. `connectorAnchor` names an
         *     enabled FederationConnector owned by the application's organization.
         */
        AuthenticationRuleEnterpriseFederationApplicationManagedPayload: {
            connectorAnchor: string;
        };
        /**
         * @description Empty payload — the connector is selected from the verified adopted
         *     domain's SSO_ONLY policy rather than by the application.
         */
        AuthenticationRuleEnterpriseFederationDomainManagedPayload: Record<string, never>;
        RealizeRuleConstraint: components["schemas"]["RealizeRuleConstraintEmail"] | components["schemas"]["RealizeRuleConstraintSteamId"] | components["schemas"]["RealizeRuleConstraintAccountAlias"] | components["schemas"]["RealizeRuleConstraintSectorSubject"] | components["schemas"]["RealizeRuleConstraintEveryone"];
        RealizeRuleConstraintCommon: {
            /** @description Per-constraint override for access token lifetime. Resolved at realize time. */
            accessTokenTtlSeconds?: number;
            /** @description Per-constraint override for refresh token lifetime. Resolved at realize time. */
            refreshTokenTtlSeconds?: number;
        };
        RealizeRuleConstraintEmail: components["schemas"]["RealizeRuleConstraintCommon"] & {
            /** @enum {string} */
            constraintType: "EMAIL";
            payload: components["schemas"]["RealizeRuleEmailPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            constraintType: "EMAIL";
        };
        RealizeRuleConstraintSteamId: components["schemas"]["RealizeRuleConstraintCommon"] & {
            /** @enum {string} */
            constraintType: "STEAM_ID";
            payload: components["schemas"]["RealizeRuleSteamIdPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            constraintType: "STEAM_ID";
        };
        RealizeRuleConstraintAccountAlias: components["schemas"]["RealizeRuleConstraintCommon"] & {
            /** @enum {string} */
            constraintType: "ACCOUNT_ALIAS";
            payload: components["schemas"]["RealizeRuleAccountAliasPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            constraintType: "ACCOUNT_ALIAS";
        };
        RealizeRuleConstraintSectorSubject: components["schemas"]["RealizeRuleConstraintCommon"] & {
            /** @enum {string} */
            constraintType: "SECTOR_SUBJECT";
            payload: components["schemas"]["RealizeRuleSectorSubjectPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            constraintType: "SECTOR_SUBJECT";
        };
        RealizeRuleConstraintEveryone: components["schemas"]["RealizeRuleConstraintCommon"] & {
            /** @enum {string} */
            constraintType: "EVERYONE";
            payload: components["schemas"]["RealizeRuleEveryonePayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            constraintType: "EVERYONE";
        };
        RealizeRuleEmailPayload: {
            /**
             * @description List of email addresses or glob patterns the realized identity
             *     must match.
             */
            allowedEmails: string[];
        };
        /**
         * @description Per-realize-time check against the realized account's SteamID64.
         *     Each entry is either the literal `"*"` (wildcard, allow any
         *     Steam identity) or a decimal SteamID64 string.
         */
        RealizeRuleSteamIdPayload: {
            allowedSteamIds: string[];
        };
        /**
         * @description Exact match on the account alias shared by the user. Wildcards are not
         *     supported, and a new account cannot match a pre-existing alias list.
         *     Values are opaque and compared exactly.
         */
        RealizeRuleAccountAliasPayload: {
            allowedAccountAliases: string[];
        };
        /**
         * @description Exact match on the application-visible token `sub`. Wildcards are not
         *     supported. A rotated subject must be allow-listed separately. Values
         *     are opaque and compared exactly.
         */
        RealizeRuleSectorSubjectPayload: {
            allowedSectorSubjects: string[];
        };
        /**
         * @description Empty payload — the explicit EVERYONE constraint admits any realized
         *     identity on this side of the Layer-2 AND boundary.
         */
        RealizeRuleEveryonePayload: Record<string, never>;
        ReturnMethodDeclaration: components["schemas"]["ReturnMethodCallback"] | components["schemas"]["ReturnMethodStatusPoll"] | components["schemas"]["ReturnMethodReveal"];
        ReturnMethodCallback: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CALLBACK";
            payload: {
                /**
                 * @description Concrete callback URL for this inquiry. The host MUST match
                 *     one of the application's allowed callback domains. The scheme
                 *     MUST be HTTPS except loopback HTTP for local development
                 *     (`localhost`, `127.0.0.1`, `[::1]`). After realization,
                 *     Connect appends the canonical `exposure-key` and
                 *     `confirmation-key` query parameters. Existing query parameters
                 *     and fragments are preserved; caller-supplied or duplicate
                 *     values for the two canonical names are overwritten. The URL
                 *     MUST be concrete and MUST NOT contain Inquiry-key templates.
                 *     Length is measured in UTF-8 bytes.
                 */
                callbackUrl: string;
            };
        };
        ReturnMethodStatusPoll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "STATUS_POLL";
            /** @description Empty payload — STATUS_POLL carries no per-inquiry parameters. */
            payload: Record<string, never>;
        };
        ReturnMethodReveal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "REVEAL";
            /**
             * @description Empty payload. Tokens are surfaced directly in the UI at
             *     realize time and the inquiry is marked redeemed immediately;
             *     any subsequent `/redeem` for the same inquiry fails with
             *     `InquiryAlreadyRedeemed`.
             */
            payload: Record<string, never>;
        };
        /**
         * @description Error response body. Known failures may include a stable `reason`.
         *     Some failures are status-only and have an empty body. A missing,
         *     malformed, or structurally invalid JSON body returns `InvalidBody`.
         */
        Error: {
            /** @description Stable machine-readable reason code. */
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Prevent storage of the credential-bearing response. */
        CredentialCacheControl: "no-store";
        /** @description Legacy cache instruction retained for credential responses. */
        CredentialPragma: "no-cache";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The API invocation path is operational and reports the deployed
             *     service identity. This response does not assert dependency,
             *     configuration, or business-capability readiness.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    establish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstablishRequest"];
            };
        };
        responses: {
            /** @description Inquiry established. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishResponse"];
                };
            };
            /** @description Client-auth JWT missing, malformed, expired, or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Application is not ACTIVE, or its parent Sector or Organization is
             *     unavailable.
             *     Reason `ApplicationNotActive`.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    statusPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPollRequest"];
            };
        };
        responses: {
            /** @description Current status of the inquiry. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPollResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    redeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Tokens issued. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemResponse"];
                };
            };
            /**
             * @description The inquiry could not be redeemed. The `reason` distinguishes:
             *
             *     - `InquiryNotFound` — the supplied key triple is not valid.
             *     - `InquiryExpired` — the inquiry has expired.
             *     - `InquiryNotRealized` — authentication is not complete.
             *     - `InquiryAlreadyRedeemed` — the single-use inquiry was consumed.
             *     - `ApplicationNotFound`, `AuthenticationNotFound`, or
             *       `AccountNotFound` — required issuance authority is unavailable.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The attempt was refused. The `reason` distinguishes:
             *
             *     - `ApplicationNotActive` — the application is unavailable.
             *     - `AccountDisabled` — the realizing account is disabled.
             *     - `AccountDeleted` — the realizing account has been erased.
             *     - `ClaimConsentRequired` — interactive login is required to
             *       establish the current claim grant.
             *     - `RequiredClaimDataMissing` — a REQUIRED claim cannot currently
             *       be disclosed. An approved account without a surname is not
             *       missing data and discloses an empty surname.
             *     - `EmailDomainBlocked`, `EmailDomainRequiresSso`, or
             *       `SsoAuthorityConflict` — current email-domain policy prevents
             *       issuance.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Reason `AuthorizationArtifactStale`: identity authority changed
             *     after authentication. Start a new inquiry before retrying.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoRequest"];
            };
        };
        responses: {
            /** @description Application metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
