/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe for the Connect service. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/establish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Establish a new authentication inquiry for an application.
         * @description Creates a new authentication inquiry under the calling application.
         *
         *     The request MUST carry a client-auth JWT in the `Authorization` header
         *     using the `SudomimusClientJWT` scheme. The JWT binds the request body
         *     bytes via a `body_sha256` claim and carries a single-use `jti` to
         *     prevent replay. See the `SudomimusClientJWT` security scheme below
         *     for the full claim contract.
         *
         *     All three narrowing fields (`authenticationConstraints`,
         *     `realizeConstraints`, `returnMethods`) are optional. When absent the
         *     inquiry imposes no per-inquiry narrowing on that layer. When present
         *     the array MUST be non-empty — an empty array is explicitly rejected
         *     with HTTP 400.
         *
         */
        post: operations["establish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status-poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll the realization status of an authentication inquiry. */
        post: operations["statusPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem a realized inquiry for an application token pair. */
        post: operations["redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token and issue a new access token.
         * @description Issues a new access token AND a new refresh token, atomically
         *     invalidating the presented refresh token. The Connect service
         *     implements OAuth 2.1 BCP §4.14.2 strict refresh-token rotation:
         *     every successful `/refresh` rotates the refresh token, and any
         *     subsequent presentation of the parent token (the one just
         *     consumed) is treated as evidence of compromise.
         *
         *     On compromise, the entire refresh-token family that the replayed
         *     token belongs to is revoked in a single sweep and the caller must
         *     re-authenticate via the normal Connect inquiry flow
         *     (`/establish` → `/status-poll` → `/redeem`). The same outcome
         *     applies when a concurrent rotation race is lost — per BCP §4.14.2
         *     a perfectly-timed retry is indistinguishable from an attacker
         *     racing the legitimate caller, so both paths count as compromise.
         *
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch localized public metadata about an application. */
        post: operations["info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether the session behind an access token is still valid.
         * @description Returns the revocation status of the refresh token (session) that the
         *     supplied access token descends from. Intended for strict applications
         *     that want near-real-time revocation: validate the access token offline
         *     as usual, then call this endpoint — caching the result for at least
         *     `recommendedRecheckSeconds` — to decide whether to keep trusting it.
         *
         *     The access token is self-authenticating: its signature is verified
         *     against the issuing application's public key, so no client-auth JWT is
         *     required. The access token's own expiry is NOT enforced here; the answer
         *     describes the underlying session, not the access token's freshness.
         *
         */
        post: operations["introspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the session behind a refresh token.
         * @description Revokes the single session identified by the supplied refresh token
         *     (RFC 7009 style). Possession of a genuine refresh token authorizes the
         *     revocation, so no client-auth JWT is required.
         *
         *     The operation is idempotent: a token that is already revoked or expired
         *     reports `revoked: true`, and a token that cannot be resolved reports
         *     `revoked: false` without revealing whether it ever existed.
         *
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke every session of an account for the calling application.
         * @description Revokes all refresh tokens belonging to the given account that were
         *     issued for the calling application (log out everywhere). This is an
         *     application-authority action — not something a single session capability
         *     can authorize — so it requires a client-auth JWT, exactly like
         *     /establish. Revocation is scoped to the calling application; sessions of
         *     the same account under other applications are unaffected.
         *
         */
        post: operations["revokeAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ready: boolean;
            service: string;
            version: string;
        };
        EstablishRequest: {
            /** @description Public anchor identifying the integrating application. */
            applicationAnchor: string;
            /** @description Optional per-inquiry narrowing of the application's
             *     authentication-rule layer. Absent means no narrowing. If present,
             *     the array MUST be non-empty; empty arrays are rejected with 400.
             *      */
            authenticationConstraints?: components["schemas"]["AuthenticationRuleConstraint"][];
            /** @description Optional per-inquiry narrowing of the application's realize-rule
             *     layer. Absent means no narrowing. If present, the array MUST be
             *     non-empty; empty arrays are rejected with 400.
             *      */
            realizeConstraints?: components["schemas"]["RealizeRuleConstraint"][];
            /** @description Optional per-inquiry return-method declaration. Doubles as the
             *     concrete delivery info for CALLBACK (carries the callback URL).
             *     Absent means no per-inquiry narrowing (CALLBACK is unreachable
             *     for this inquiry because no URL is anchored). If present, the
             *     array MUST be non-empty; empty arrays are rejected with 400.
             *      */
            returnMethods?: components["schemas"]["ReturnMethodDeclaration"][];
        };
        EstablishResponse: {
            applicationAnchor: string;
            /** @description Public half of the inquiry key pair; safe to share with the user agent. */
            exposureKey: string;
            /** @description Private half of the inquiry key pair; must stay on the originating client. */
            hiddenKey: string;
        };
        StatusPollRequest: {
            exposureKey: string;
            hiddenKey: string;
        };
        StatusPollResponse: components["schemas"]["StatusPollPendingResponse"] | components["schemas"]["StatusPollRealizedResponse"];
        StatusPollPendingResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "PENDING";
        };
        StatusPollRealizedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "REALIZED";
            /** @description One-time key proving the inquiry has been realized; pass to /redeem. */
            confirmationKey: string;
        };
        RedeemRequest: {
            exposureKey: string;
            hiddenKey: string;
            confirmationKey: string;
        };
        RedeemResponse: {
            applicationAnchor: string;
            /** @description Long-lived refresh token (JWT). */
            refreshToken: string;
            /** @description Short-lived access token (JWT). */
            accessToken: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RefreshResponse: {
            /** @description Short-lived access token (JWT). */
            accessToken: string;
            /** @description Newly issued refresh token (JWT). The presented refresh
             *     token is invalidated atomically as part of the same call;
             *     re-presenting it is treated as compromise under OAuth 2.1
             *     BCP §4.14.2 strict rotation.
             *      */
            refreshToken: string;
        };
        InfoRequest: {
            applicationAnchor: string;
            /** @description IETF BCP 47 locale tag (e.g. "en-US"). Falls back to the application's default locale if not available. */
            locale: string;
        };
        InfoResponse: {
            applicationAnchor: string;
            /** @description Localized application display name. */
            applicationName: string;
            /** @description PEM-encoded application public key used to verify issued JWTs. */
            applicationPublicKey: string;
        };
        IntrospectRequest: {
            /** @description A Sudomimus-issued access token (JWT). Its signature is verified; its own expiry is not enforced. */
            accessToken: string;
        };
        IntrospectResponse: {
            /**
             * @description Revocation state of the session behind the access token. `not_found`
             *     covers an unknown session or one belonging to a different application.
             *
             * @enum {string}
             */
            status: "active" | "revoked" | "expired" | "not_found";
            /** @description Suggested minimum number of seconds to cache this result before re-checking. */
            recommendedRecheckSeconds: number;
        };
        LogoutRequest: {
            /** @description The refresh token (JWT) whose session should be revoked. */
            refreshToken: string;
        };
        LogoutResponse: {
            /** @description True if the session is now revoked, including sessions that were already revoked or expired. */
            revoked: boolean;
        };
        RevokeAllRequest: {
            /** @description Identifier of the account whose sessions should be revoked for the calling application. */
            accountIdentifier: string;
        };
        RevokeAllResponse: {
            /** @description Number of refresh tokens that were revoked. */
            revokedCount: number;
        };
        AuthenticationRuleConstraint: {
            /**
             * @description Which authentication method this constraint narrows to.
             * @enum {string}
             */
            method: "PASSKEY" | "EMAIL_VERIFICATION" | "STEAM_TICKET" | "STEAM_OPENID" | "ACCESS_KEY_DIRECT" | "GOOGLE_OAUTH" | "GITHUB_OAUTH" | "DISCORD_OAUTH";
            payload: components["schemas"]["AuthenticationRulePasskeyPayload"] | components["schemas"]["AuthenticationRuleEmailVerificationPayload"] | components["schemas"]["AuthenticationRuleSteamTicketPayload"] | components["schemas"]["AuthenticationRuleSteamOpenIdPayload"] | components["schemas"]["AuthenticationRuleAccessKeyDirectPayload"] | components["schemas"]["AuthenticationRuleGoogleOAuthPayload"] | components["schemas"]["AuthenticationRuleGitHubOAuthPayload"] | components["schemas"]["AuthenticationRuleDiscordOAuthPayload"];
            /** @description Per-constraint override for access token lifetime. Resolved at realize time. */
            accessTokenTtlSeconds?: number;
            /** @description Per-constraint override for refresh token lifetime. Resolved at realize time. */
            refreshTokenTtlSeconds?: number;
        };
        /** @description Passkey-method payload. `allowUsernameless` opts the application
         *     in to discoverable-credential ("usernameless") passkey login,
         *     where the user authenticates without first entering an email.
         *     Absent or `false` keeps the email-first flow; only the entry
         *     path is affected — realize authorization is still decided
         *     entirely by Layer 2.
         *      */
        AuthenticationRulePasskeyPayload: {
            allowUsernameless?: boolean;
        };
        /** @description Empty payload — email-verification constraints carry no further parameters. */
        AuthenticationRuleEmailVerificationPayload: Record<string, never>;
        /** @description Steam-native-ticket payload. Gates native-api's
         *     `/direct-issue/steam-ticket` flow. `allowedSteamAppIds` is the
         *     non-empty list of Steam App IDs whose tickets are accepted.
         *      */
        AuthenticationRuleSteamTicketPayload: {
            allowedSteamAppIds: number[];
        };
        /** @description Steam OpenID 2.0 carries no app-id concept (that is
         *     native-ticket-specific). Any Steam account is accepted as long
         *     as the application's rule set allows STEAM_OPENID at all.
         *      */
        AuthenticationRuleSteamOpenIdPayload: Record<string, never>;
        /** @description Gates native-api's `/direct-issue/access-key` flow. Credentials
         *     live in the dedicated `AccessKeyCredential` table; no row of
         *     this method ever appears in the `Authentication` table.
         *      */
        AuthenticationRuleAccessKeyDirectPayload: Record<string, never>;
        /** @description Phase 1: any Google account is accepted as long as the
         *     application's rule set allows GOOGLE_OAUTH at all. A later
         *     phase will add `allowedHostedDomains: string[]` for Google
         *     Workspace gating.
         *      */
        AuthenticationRuleGoogleOAuthPayload: Record<string, never>;
        /** @description Empty `allowedGitHubOrgs` array means no org gating — any
         *     GitHub account is accepted. Non-empty means the user must be a
         *     member of at least one listed organization (case-insensitive
         *     match on the org `login`). The `read:org` OAuth scope is only
         *     requested when at least one matching rule carries a non-empty
         *     allowlist; applications without org gating keep the minimal
         *     `read:user user:email` consent screen.
         *      */
        AuthenticationRuleGitHubOAuthPayload: {
            allowedGitHubOrgs: string[];
        };
        /** @description Phase 1: any Discord account is accepted as long as the
         *     application's rule set allows DISCORD_OAUTH at all. Phase 1.5
         *     will add `allowedDiscordGuilds: string[]` for guild (server)
         *     gating, which will additionally request the `guilds` OAuth
         *     scope and fetch `GET /users/@me/guilds`.
         *      */
        AuthenticationRuleDiscordOAuthPayload: Record<string, never>;
        RealizeRuleConstraint: {
            /**
             * @description Which realize-rule kind this constraint narrows to.
             * @enum {string}
             */
            constraintType: "EMAIL" | "STEAM_ID" | "ACCOUNT_IDENTIFIER";
            payload: components["schemas"]["RealizeRuleEmailPayload"] | components["schemas"]["RealizeRuleSteamIdPayload"] | components["schemas"]["RealizeRuleAccountIdentifierPayload"];
            /** @description Per-constraint override for access token lifetime. Resolved at realize time. */
            accessTokenTtlSeconds?: number;
            /** @description Per-constraint override for refresh token lifetime. Resolved at realize time. */
            refreshTokenTtlSeconds?: number;
        };
        RealizeRuleEmailPayload: {
            /** @description List of email addresses or glob patterns the realized identity
             *     must match. Glob patterns are bounded by server-side limits to
             *     prevent regex backtracking attacks.
             *      */
            allowedEmails: string[];
        };
        /** @description Per-realize-time check against the realized account's SteamID64.
         *     Each entry is either the literal `"*"` (wildcard, allow any
         *     Steam identity) or a decimal SteamID64 string.
         *      */
        RealizeRuleSteamIdPayload: {
            allowedSteamIds: string[];
        };
        /** @description Exact match on the realizing account's UUID. No wildcard —
         *     because the account does not yet exist during fresh
         *     registration, this constraint matches nothing for new sign-ups,
         *     so use it only for known-existing accounts.
         *      */
        RealizeRuleAccountIdentifierPayload: {
            allowedAccountIdentifiers: string[];
        };
        ReturnMethodDeclaration: components["schemas"]["ReturnMethodCallback"] | components["schemas"]["ReturnMethodStatusPoll"] | components["schemas"]["ReturnMethodReveal"] | components["schemas"]["ReturnMethodDirectIssue"] | components["schemas"]["ReturnMethodOidc"];
        ReturnMethodCallback: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CALLBACK";
            payload: {
                /** @description Concrete callback URL for this inquiry. The host MUST match
                 *     one of the application's allowed callback domains.
                 *      */
                callbackUrl: string;
            };
        };
        ReturnMethodStatusPoll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "STATUS_POLL";
            /** @description Empty payload — STATUS_POLL carries no per-inquiry parameters. */
            payload: Record<string, never>;
        };
        ReturnMethodReveal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "REVEAL";
            /** @description Empty payload. Tokens are surfaced directly in the UI at
             *     realize time and the inquiry is marked redeemed immediately;
             *     any subsequent `/redeem` for the same inquiry fails with
             *     `InquiryAlreadyRedeemed`.
             *      */
            payload: Record<string, never>;
        };
        ReturnMethodDirectIssue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DIRECT_ISSUE";
            /** @description Empty payload. Opts the application in to native-api's
             *     direct-issue flows (`/direct-issue/steam-ticket`,
             *     `/direct-issue/access-key`). Per-inquiry payload is empty
             *     because direct-issue does not flow through `/establish`.
             *      */
            payload: Record<string, never>;
        };
        ReturnMethodOidc: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OIDC";
            /** @description Accepted on the wire for symmetry, but in practice OIDC is
             *     not declared per-inquiry — the OIDC API drives its own
             *     inquiry against Connect via CALLBACK-to-self. The matching
             *     per-inquiry payload is therefore empty.
             *      */
            payload: Record<string, never>;
        };
        /** @description Error response body. The Connect service emits `{ "reason": "<SymbolDescription>" }`
         *     for known failure modes. When the reason symbol's description begins with
         *     `PRIVATE`, the body is empty (zero bytes) and only the HTTP status carries
         *     signal — both `reason` and the body itself are absent in that case.
         *      */
        Error: {
            /** @description Stable machine-readable reason code. */
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    establish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstablishRequest"];
            };
        };
        responses: {
            /** @description Inquiry established. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishResponse"];
                };
            };
            /** @description Client-auth JWT missing, malformed, expired, or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Application has been disabled via the admin kill switch.
             *     Reason `ApplicationDisabled`.
             *      */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    statusPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPollRequest"];
            };
        };
        responses: {
            /** @description Current status of the inquiry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPollResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    redeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemResponse"];
                };
            };
            /** @description The inquiry could not be redeemed. The `reason` distinguishes:
             *
             *     - `InquiryNotFound` — the `(exposureKey, hiddenKey,
             *       confirmationKey)` triple does not resolve to a realized
             *       inquiry.
             *     - `InquiryNotRealized` — the inquiry exists but has not been
             *       realized yet.
             *     - `InquiryAlreadyRedeemed` — the inquiry has already been
             *       consumed (single-use guard via conditional write; also
             *       fires after a REVEAL realize that surfaces the tokens
             *       in-line and immediately marks the inquiry redeemed).
             *      */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Application has been disabled via the admin kill switch.
             *     Reason `ApplicationDisabled`.
             *      */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New access token and rotated refresh token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Refresh token rejected. The `reason` distinguishes:
             *
             *     - `RefreshTokenNotFound` — token cannot be resolved (unknown
             *       `jti`, wrong signature, or otherwise invalid).
             *     - `RefreshTokenSuspended` — the row is administratively
             *       suspended.
             *     - `RefreshTokenExpired` — the token is past its `exp`.
             *     - `RefreshTokenFamilyCompromised` — the presented token had
             *       already been rotated; the whole family has now been
             *       revoked.
             *     - `RefreshTokenRotationRaceLost` — a concurrent rotation won
             *       the conditional write. Per OAuth 2.1 BCP §4.14.2 this is
             *       also treated as compromise and the family is revoked.
             *      */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoRequest"];
            };
        };
        responses: {
            /** @description Application metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    introspect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntrospectRequest"];
            };
        };
        responses: {
            /** @description Status of the session behind the access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntrospectResponse"];
                };
            };
            /** @description Access token missing, malformed, or with an invalid signature. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Revocation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeAllRequest"];
            };
        };
        responses: {
            /** @description Number of sessions revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeAllResponse"];
                };
            };
            /** @description Client-auth JWT missing, malformed, expired, or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
