/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe for the Connect service. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/establish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Establish a new authentication inquiry for an application.
         * @description Creates a new authentication inquiry under the calling application.
         *
         *     The request MUST carry a client-auth JWT in the `Authorization` header
         *     using the `SudomimusClientJWT` scheme. The JWT binds the request body
         *     bytes via a `body_sha256` claim and carries a single-use `jti` to
         *     prevent replay. See the `SudomimusClientJWT` security scheme below
         *     for the full claim contract.
         *
         *     All three narrowing fields (`authenticationConstraints`,
         *     `realizeConstraints`, `returnMethods`) are optional. When absent the
         *     inquiry imposes no per-inquiry narrowing on that layer. When present
         *     the array MUST be non-empty — an empty array is explicitly rejected
         *     with HTTP 400.
         */
        post: operations["establish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status-poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll the realization status of an authentication inquiry. */
        post: operations["statusPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem a realized inquiry for an application token pair. */
        post: operations["redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch localized public metadata about an application. */
        post: operations["info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ready: boolean;
            service: string;
            version: string;
        };
        EstablishRequest: {
            /** @description Public anchor identifying the integrating application. */
            applicationAnchor: string;
            /**
             * @description Optional per-inquiry narrowing of the application's
             *     authentication-rule layer. Absent means no narrowing. If present,
             *     the array MUST be non-empty; empty arrays are rejected with 400.
             */
            authenticationConstraints?: components["schemas"]["AuthenticationRuleConstraint"][];
            /**
             * @description Optional per-inquiry narrowing of the application's realize-rule
             *     layer. Absent means no narrowing. If present, the array MUST be
             *     non-empty; empty arrays are rejected with 400.
             */
            realizeConstraints?: components["schemas"]["RealizeRuleConstraint"][];
            /**
             * @description Optional per-inquiry return-method declaration. Doubles as the
             *     concrete delivery info for CALLBACK (carries the callback URL).
             *     Absent means no per-inquiry narrowing (CALLBACK is unreachable
             *     for this inquiry because no URL is anchored). If present, the
             *     array MUST be non-empty; empty arrays are rejected with 400.
             */
            returnMethods?: components["schemas"]["ReturnMethodDeclaration"][];
        };
        EstablishResponse: {
            applicationAnchor: string;
            /** @description Public half of the inquiry key pair; safe to share with the user agent. */
            exposureKey: string;
            /** @description Private half of the inquiry key pair; must stay on the originating client. */
            hiddenKey: string;
        };
        StatusPollRequest: {
            exposureKey: string;
            hiddenKey: string;
        };
        StatusPollResponse: components["schemas"]["StatusPollPendingResponse"] | components["schemas"]["StatusPollRealizedResponse"];
        StatusPollPendingResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "PENDING";
        };
        StatusPollRealizedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "REALIZED";
            /** @description One-time key proving the inquiry has been realized; pass to /redeem. */
            confirmationKey: string;
        };
        RedeemRequest: {
            exposureKey: string;
            hiddenKey: string;
            confirmationKey: string;
        };
        /**
         * @description One shareable claim: what the application requests (`requirement`)
         *     joined with the user's standing decision (`state`). `UNKNOWN` means
         *     the user was never asked; `DENIED` means the user explicitly
         *     declined.
         */
        ClaimRequirementStateView: {
            /**
             * @description The developer's policy for the claim. `SYNTHETIC` guarantees the
             *     claim is present but permits a generated placeholder (a stand-in
             *     name, a proxy email) when the user has not shared real data —
             *     unlike `REQUIRED` it never blocks issuance or raises an errand.
             * @enum {string}
             */
            requirement: "OFF" | "OPTIONAL" | "REQUIRED" | "SYNTHETIC";
            /** @enum {string} */
            state: "UNKNOWN" | "GRANTED" | "DENIED";
        };
        /**
         * @description Per-claim view across the three shareable claims — why a claim is
         *     or is not present in the minted token (policy OFF, never asked,
         *     declined, or granted).
         */
        ClaimsStateView: {
            email: components["schemas"]["ClaimRequirementStateView"];
            firstName: components["schemas"]["ClaimRequirementStateView"];
            lastName: components["schemas"]["ClaimRequirementStateView"];
        };
        RedeemResponse: {
            claims: components["schemas"]["ClaimsStateView"];
            applicationAnchor: string;
            /**
             * @description Long-lived refresh token (JWT). Decode its body to
             *     `RefreshTokenBody` (see schema). The refresh token leaves the
             *     system, so its body carries the sector `subject`, never the
             *     underlying account identifier.
             */
            refreshToken: string;
            /**
             * @description Short-lived access token (JWT). Decode its body to
             *     `AccessTokenBody` (see schema) — the application-visible user
             *     key is the `subject` (sector subject) claim.
             */
            accessToken: string;
        };
        /**
         * @description Decoded body (payload) of a Sudomimus access token. The standard
         *     JWT envelope claims (`iss`, `aud`, `iat`, `exp`, `jti`, `kty`,
         *     `sub`) live in the JWT *header*; this object is the body. The
         *     application keys its users on `subject`. The `firstName`,
         *     `lastName`, and `emailAddress` claims are consent-gated (claim
         *     sharing): each is minted only when the application's claim policy
         *     permits it AND the user has granted that claim, so any of them may
         *     be absent. The exception is a `SYNTHETIC` claim policy: that field is
         *     instead always present, carrying a generated placeholder (a stand-in
         *     name, a proxy email) whenever the user has not shared real data.
         */
        AccessTokenBody: {
            /**
             * @description The application-visible user identifier — the per-(account,
             *     sector) **sector subject**, also the OIDC `sub`. This is the
             *     value an application keys its users on; the underlying account
             *     identifier never appears in a token. User-rotatable.
             *     Opaque: never parse or format-validate it.
             */
            subject: string;
            /**
             * @description Given name. Minted only when the application's claim policy
             *     permits it AND the user has granted the claim; may be absent
             *     even when the account has a value stored. Under a `SYNTHETIC`
             *     policy it is always present, possibly a placeholder name.
             */
            firstName?: string;
            /** @description Family name. Same consent gating as `firstName`. */
            lastName?: string;
            /**
             * @description Email associated with this login. Consent-gated like
             *     `firstName` / `lastName` (minted only when policy permits AND
             *     the user granted the EMAIL claim). When a real value is included:
             *     the exact email typed for email-OTP logins, otherwise the
             *     account's primary email; omitted for accounts with no verified
             *     email (e.g. Steam-only or AccessKey-only). The exception is a
             *     `SYNTHETIC` email policy: the field is then always present — a
             *     real verified email when shared, otherwise a
             *     `…@proxy.sudomimus.email` proxy address (best-effort forwarding,
             *     not guaranteed; not a verified mailbox).
             */
            emailAddress?: string;
        };
        /**
         * @description Decoded body (payload) of a Sudomimus refresh token. Carries the
         *     sector `subject` (the same pairwise identifier as the access-token
         *     body) because the refresh token leaves the system and must never
         *     expose the underlying account identifier. Informational only —
         *     `/refresh` resolves the token by its `jti`, not by reading the body.
         */
        RefreshTokenBody: {
            /**
             * @description The application-visible **sector subject**. Opaque: never
             *     parse or format-validate it.
             */
            subject: string;
        };
        InfoRequest: {
            applicationAnchor: string;
            /** @description IETF BCP 47 locale tag (e.g. "en-US"). Falls back to the application's default locale if not available. */
            locale: string;
        };
        InfoResponse: {
            applicationAnchor: string;
            /** @description Localized application display name. */
            applicationName: string;
            /** @description PEM-encoded application public key used to verify issued JWTs. */
            applicationPublicKey: string;
        };
        AuthenticationRuleConstraint: {
            /**
             * @description Which authentication method this constraint narrows to.
             * @enum {string}
             */
            method: "PASSKEY_USERNAMELESS" | "PASSKEY_REASONED" | "EMAIL_VERIFICATION" | "STEAM_TICKET" | "STEAM_OPENID" | "ACCESS_KEY_DIRECT" | "GOOGLE_OAUTH" | "GITHUB_OAUTH" | "DISCORD_OAUTH" | "BATTLENET_OAUTH" | "X_OAUTH";
            payload: components["schemas"]["AuthenticationRulePasskeyUsernamelessPayload"] | components["schemas"]["AuthenticationRulePasskeyReasonedPayload"] | components["schemas"]["AuthenticationRuleEmailVerificationPayload"] | components["schemas"]["AuthenticationRuleSteamTicketPayload"] | components["schemas"]["AuthenticationRuleSteamOpenIdPayload"] | components["schemas"]["AuthenticationRuleAccessKeyDirectPayload"] | components["schemas"]["AuthenticationRuleGoogleOAuthPayload"] | components["schemas"]["AuthenticationRuleGitHubOAuthPayload"] | components["schemas"]["AuthenticationRuleDiscordOAuthPayload"] | components["schemas"]["AuthenticationRuleBattleNetOAuthPayload"] | components["schemas"]["AuthenticationRuleXOAuthPayload"];
            /** @description Per-constraint override for access token lifetime. Resolved at realize time. */
            accessTokenTtlSeconds?: number;
            /** @description Per-constraint override for refresh token lifetime. Resolved at realize time. */
            refreshTokenTtlSeconds?: number;
        };
        /**
         * @description Empty payload — narrows to usernameless (discoverable-credential)
         *     passkey login, the "Sign in with a passkey" entry shown before any
         *     email is entered. Realize authorization is still decided by Layer 2.
         */
        AuthenticationRulePasskeyUsernamelessPayload: Record<string, never>;
        /**
         * @description Empty payload — narrows to email-first ("reasoned") passkey login,
         *     the passkey option offered after the user enters their email.
         *     Realize authorization is still decided by Layer 2.
         */
        AuthenticationRulePasskeyReasonedPayload: Record<string, never>;
        /** @description Empty payload — email-verification constraints carry no further parameters. */
        AuthenticationRuleEmailVerificationPayload: Record<string, never>;
        /**
         * @description Steam-native-ticket payload. Gates native-api's
         *     `/direct-issue/steam-ticket` flow. `allowedSteamAppIds` is the
         *     non-empty list of Steam App IDs whose tickets are accepted.
         */
        AuthenticationRuleSteamTicketPayload: {
            allowedSteamAppIds: number[];
        };
        /**
         * @description Steam OpenID 2.0 carries no app-id concept (that is
         *     native-ticket-specific). Any Steam account is accepted as long
         *     as the application's rule set allows STEAM_OPENID at all.
         */
        AuthenticationRuleSteamOpenIdPayload: Record<string, never>;
        /**
         * @description Gates native-api's `/direct-issue/access-key` flow. Credentials
         *     live in the dedicated `AccessKeyCredential` table; no row of
         *     this method ever appears in the `Authentication` table.
         */
        AuthenticationRuleAccessKeyDirectPayload: Record<string, never>;
        /**
         * @description Phase 1: any Google account is accepted as long as the
         *     application's rule set allows GOOGLE_OAUTH at all. A later
         *     phase will add `allowedHostedDomains: string[]` for Google
         *     Workspace gating.
         */
        AuthenticationRuleGoogleOAuthPayload: Record<string, never>;
        /**
         * @description Empty `allowedGitHubOrgs` array means no org gating — any
         *     GitHub account is accepted. Non-empty means the user must be a
         *     member of at least one listed organization (case-insensitive
         *     match on the org `login`). The `read:org` OAuth scope is only
         *     requested when at least one matching rule carries a non-empty
         *     allowlist; applications without org gating keep the minimal
         *     `read:user user:email` consent screen.
         */
        AuthenticationRuleGitHubOAuthPayload: {
            allowedGitHubOrgs: string[];
        };
        /**
         * @description Phase 1: any Discord account is accepted as long as the
         *     application's rule set allows DISCORD_OAUTH at all. Phase 1.5
         *     will add `allowedDiscordGuilds: string[]` for guild (server)
         *     gating, which will additionally request the `guilds` OAuth
         *     scope and fetch `GET /users/@me/guilds`.
         */
        AuthenticationRuleDiscordOAuthPayload: Record<string, never>;
        /**
         * @description Battle.net (Blizzard) has no per-application gating concept, so any
         *     Battle.net account is accepted as long as the application's rule set
         *     allows BATTLENET_OAUTH at all. Empty payload. Battle.net is an
         *     email-less provider, so Layer-2 EMAIL rules fail closed against a
         *     Battle.net-only account.
         */
        AuthenticationRuleBattleNetOAuthPayload: Record<string, never>;
        /**
         * @description X (formerly Twitter) has no per-application gating concept, so any
         *     X account is accepted as long as the application's rule set allows
         *     X_OAUTH at all. Empty payload. X is an email-less provider, so
         *     Layer-2 EMAIL rules fail closed against an X-only account.
         */
        AuthenticationRuleXOAuthPayload: Record<string, never>;
        RealizeRuleConstraint: {
            /**
             * @description Which realize-rule kind this constraint narrows to.
             * @enum {string}
             */
            constraintType: "EMAIL" | "STEAM_ID" | "ACCOUNT_ALIAS" | "SECTOR_SUBJECT";
            payload: components["schemas"]["RealizeRuleEmailPayload"] | components["schemas"]["RealizeRuleSteamIdPayload"] | components["schemas"]["RealizeRuleAccountAliasPayload"] | components["schemas"]["RealizeRuleSectorSubjectPayload"];
            /** @description Per-constraint override for access token lifetime. Resolved at realize time. */
            accessTokenTtlSeconds?: number;
            /** @description Per-constraint override for refresh token lifetime. Resolved at realize time. */
            refreshTokenTtlSeconds?: number;
        };
        RealizeRuleEmailPayload: {
            /**
             * @description List of email addresses or glob patterns the realized identity
             *     must match. Glob patterns are bounded by server-side limits to
             *     prevent regex backtracking attacks.
             */
            allowedEmails: string[];
        };
        /**
         * @description Per-realize-time check against the realized account's SteamID64.
         *     Each entry is either the literal `"*"` (wildcard, allow any
         *     Steam identity) or a decimal SteamID64 string.
         */
        RealizeRuleSteamIdPayload: {
            allowedSteamIds: string[];
        };
        /**
         * @description Exact match on the realizing account's **account alias** — the
         *     user-visible, application-invisible, rotatable handle the user
         *     reads in the With portal and shares out-of-band with whoever
         *     configures the rule. No wildcard — because the account does not
         *     yet exist during fresh registration, this constraint matches
         *     nothing for new sign-ups. The alias is opaque: it is compared by
         *     exact-string equality and never parsed or format-validated.
         */
        RealizeRuleAccountAliasPayload: {
            allowedAccountAliases: string[];
        };
        /**
         * @description Exact match on the realizing account's **sector subject** for the
         *     realizing application's sector — the application-visible token
         *     `sub` the owner already sees in their own logs. No wildcard.
         *     Rotating the subject locks the user out (it becomes a brand-new,
         *     not-yet-allow-listed identity) rather than letting them bypass the
         *     rule. The subject is opaque: compared by exact-string equality and
         *     never parsed or format-validated.
         */
        RealizeRuleSectorSubjectPayload: {
            allowedSectorSubjects: string[];
        };
        ReturnMethodDeclaration: components["schemas"]["ReturnMethodCallback"] | components["schemas"]["ReturnMethodStatusPoll"] | components["schemas"]["ReturnMethodReveal"] | components["schemas"]["ReturnMethodDirectIssue"] | components["schemas"]["ReturnMethodOidc"];
        ReturnMethodCallback: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CALLBACK";
            payload: {
                /**
                 * @description Concrete callback URL for this inquiry. The host MUST match
                 *     one of the application's allowed callback domains.
                 */
                callbackUrl: string;
            };
        };
        ReturnMethodStatusPoll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "STATUS_POLL";
            /** @description Empty payload — STATUS_POLL carries no per-inquiry parameters. */
            payload: Record<string, never>;
        };
        ReturnMethodReveal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "REVEAL";
            /**
             * @description Empty payload. Tokens are surfaced directly in the UI at
             *     realize time and the inquiry is marked redeemed immediately;
             *     any subsequent `/redeem` for the same inquiry fails with
             *     `InquiryAlreadyRedeemed`.
             */
            payload: Record<string, never>;
        };
        ReturnMethodDirectIssue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DIRECT_ISSUE";
            /**
             * @description Empty payload. Opts the application in to native-api's
             *     direct-issue flows (`/direct-issue/steam-ticket`,
             *     `/direct-issue/access-key`). Per-inquiry payload is empty
             *     because direct-issue does not flow through `/establish`.
             */
            payload: Record<string, never>;
        };
        ReturnMethodOidc: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OIDC";
            /**
             * @description Accepted on the wire for symmetry, but in practice OIDC is
             *     not declared per-inquiry — the OIDC API drives its own
             *     inquiry against Connect via CALLBACK-to-self. The matching
             *     per-inquiry payload is therefore empty.
             */
            payload: Record<string, never>;
        };
        /**
         * @description Error response body. The Connect service emits `{ "reason": "<SymbolDescription>" }`
         *     for known failure modes. When the reason symbol's description begins with
         *     `PRIVATE`, the body is empty (zero bytes) and only the HTTP status carries
         *     signal — both `reason` and the body itself are absent in that case.
         */
        Error: {
            /** @description Stable machine-readable reason code. */
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    establish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstablishRequest"];
            };
        };
        responses: {
            /** @description Inquiry established. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishResponse"];
                };
            };
            /** @description Client-auth JWT missing, malformed, expired, or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Application is disabled.
             *     Reason `ApplicationDisabled`.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    statusPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPollRequest"];
            };
        };
        responses: {
            /** @description Current status of the inquiry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPollResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    redeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemResponse"];
                };
            };
            /**
             * @description The inquiry could not be redeemed. The `reason` distinguishes:
             *
             *     - `InquiryNotFound` — the `(exposureKey, hiddenKey,
             *       confirmationKey)` triple does not resolve to a realized
             *       inquiry.
             *     - `InquiryExpired` — the inquiry resolved but its lifetime has
             *       elapsed (expired by TTL or out of polling attempts).
             *     - `InquiryNotRealized` — the inquiry exists but has not been
             *       realized yet.
             *     - `InquiryAlreadyRedeemed` — the inquiry has already been
             *       consumed (single-use guard via conditional write; also
             *       fires after a REVEAL realize that surfaces the tokens
             *       in-line and immediately marks the inquiry redeemed).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The attempt was refused. The `reason` distinguishes:
             *
             *     - `ApplicationDisabled` — the application is disabled.
             *     - `AccountDisabled` — the realizing account is disabled.
             *     - `AccountDeleted` — the realizing account has been erased.
             *     - `ClaimConsentRequired` — the application requires a claim
             *       (email / first name / last name) the user has not granted;
             *       the standing grant must be (re)established through an
             *       interactive browser login before tokens can be issued.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoRequest"];
            };
        };
        responses: {
            /** @description Application metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
