/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Native invocation health and deployment identity. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct-issue/access-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an access-key credential for application tokens.
         * @description Exchanges an application-scoped access-key identifier and secret for
         *     access and refresh tokens. The key must belong to the named
         *     application, remain active, and satisfy its configured authorization
         *     rules. Credential rejection uses the single opaque reason
         *     `AccessKeyDirectDenied`.
         */
        post: operations["directIssueAccessKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct-issue/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an Ed25519 public-key assertion for application tokens.
         * @description Authenticates an Account or one of its Agent/Automation principals with
         *     a compact JWT signed by a registered Ed25519 key. The credential's
         *     immutable Application/Sector applicability must include the named
         *     application. Account credentials issue ordinary application access
         *     tokens; Workload credentials issue the dedicated Workload access-token
         *     type with pairwise `act.sub`. Credential rejection uses the single
         *     opaque reason `PublicKeyDirectDenied`.
         *
         *     The JOSE header must be exact `{alg:"EdDSA",
         *     typ:"vnd.sudomimus.public-key-assertion+jwt",kid:"pky_..."}`. Claims
         *     must be exact `iss`, `aud`, `iat`, `exp`, `jti`, and `requestHash`;
         *     `iss` equals `kid`, `aud` is `sudomimus-native-public-key`, lifetime is
         *     at most 60 seconds, and `requestHash` is base64url SHA-256 of the exact
         *     request-body bytes. Every retry uses a new random 128-bit `jti`.
         */
        post: operations["directIssuePublicKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct-issue/steam-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a Steam Web API auth ticket for application tokens.
         * @description The client SDK calls `ISteamUser::GetAuthTicketForWebApi("sudomimus")`
         *     (the identity string MUST be exactly `"sudomimus"`), waits for the
         *     `GetTicketForWebApiResponse_t` callback, hex-encodes the returned bytes,
         *     and submits them with the application anchor and Steam App ID. The
         *     ticket must satisfy the application's configured rules and is
         *     single-use for this exchange. Verify the returned tokens through the
         *     application's Session JWKS.
         */
        post: operations["directIssueSteamTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proactively mint an errand for a user you already authenticated.
         * @description Creates a browser handoff that lets an already authenticated user
         *     complete profile data or manage optional claim sharing. Supply a
         *     current application access token. The browser flow re-authenticates the
         *     user before making changes. If nothing is required, `errand` is `null`;
         *     otherwise open `errand.url` and optionally poll its status.
         */
        post: operations["createErrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errand/{errandKey}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll the status of an errand handoff.
         * @description Poll about every two seconds while the user completes the browser
         *     handoff, or wait for confirmation in your own UI. No additional
         *     authentication is required beyond `errandKey`. Unknown, malformed, and
         *     expired keys all report `EXPIRED`. After `COMPLETED`, retry the original
         *     direct-issue request once.
         */
        get: operations["errandStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description The API invocation path completed successfully.
             * @enum {string}
             */
            status: "ok";
            /** @description Stable runtime service identity. */
            service: string;
            /** @description Version from the deployed service's version manifest. */
            version: string;
        };
        DirectIssueAccessKeyRequest: {
            /** @description Public anchor identifying the integrating application. */
            applicationAnchor: string;
            /**
             * @description Canonical access-key identifier, including the mandatory
             *     `acs_k_` prefix followed by its UUID.
             */
            accessKeyIdentifier: string;
            /**
             * @description Canonical access-key secret, including the mandatory `acs_t_`
             *     prefix followed by 64 lowercase hexadecimal characters (32
             *     random bytes). Returned only when the access key is issued.
             */
            accessKeySecret: string;
        };
        DirectIssuePublicKeyRequest: {
            /** @description Public anchor identifying the integrating application. */
            applicationAnchor: string;
        };
        DirectIssueAccessKeyResponse: {
            claims: components["schemas"]["ClaimsStateView"];
            applicationAnchor: string;
            /**
             * @description Account credentials use media type
             *     `vnd.sudomimus.application-access+jwt`. Workload credentials use
             *     `vnd.sudomimus.workload-access+jwt` and add exact
             *     `act: {sub: <pairwise-workload-subject>}`. In both cases payload
             *     `sub` is the owner Account's pairwise sector subject, `sid`
             *     identifies the session, and `jti` identifies this token instance.
             *     The token contains no profile claims or raw Account/Workload
             *     identifier; use Session API `/userinfo` for current shared data.
             */
            accessToken: string;
            /** @description Long-lived refresh token JWT with stable payload `sid`, version identifier `jti`, and positive `rotationVersion`. It contains no user identifier. Use Session API `/refresh` for renewal without re-presenting the access key. */
            refreshToken: string;
        };
        DirectIssueSteamTicketRequest: {
            /** @description Public anchor identifying the integrating application. */
            applicationAnchor: string;
            /**
             * @description Hex-encoded Steam Web API auth ticket bytes returned from
             *     `ISteamUser::GetAuthTicketForWebApi("sudomimus")`. Hexadecimal
             *     characters are case-insensitive.
             */
            steamTicketHex: string;
            /**
             * Format: int64
             * @description Steam App ID under which the ticket was generated. Must be
             *     allow-listed by the application's `STEAM_TICKET` authentication
             *     rule. Steam binds tickets to their issuing App ID; passing a
             *     different value fails verification.
             */
            steamAppId: number;
        };
        DirectIssueSteamTicketResponse: {
            claims: components["schemas"]["ClaimsStateView"];
            applicationAnchor: string;
            /**
             * @description Short-lived access token (JWT). Payload `sub` is the pairwise
             *     sector subject, `sid` identifies the session, and
             *     `jti` identifies this token instance. It contains no profile claims
             *     or raw account identifier; use Session API `/userinfo` for current
             *     shared identity data.
             */
            accessToken: string;
            /** @description Long-lived refresh token JWT with stable payload `sid`, version identifier `jti`, and positive `rotationVersion`. It contains no user identifier. Use Session API `/refresh` to obtain a new access token without re-acquiring a Steam ticket. */
            refreshToken: string;
        };
        /**
         * @description One shareable claim: what the application requests (`requirement`)
         *     joined with the user's standing decision (`state`). `UNKNOWN` means
         *     the user was never asked; `DENIED` means the user explicitly
         *     declined.
         */
        ClaimRequirementStateView: {
            /**
             * @description The developer's policy for the claim. `SYNTHETIC_ONLY` always
             *     emits the generated placeholder and never asks for real data.
             *     `SYNTHETIC_FALLBACK` guarantees the claim is present but uses a
             *     generated placeholder (a stand-in name, a proxy email, or a
             *     generated avatar) when the user has not shared real data. Unlike `REQUIRED`, neither
             *     synthetic mode blocks issuance or raises an errand.
             * @enum {string}
             */
            requirement: "SYNTHETIC_ONLY" | "OFF" | "OPTIONAL" | "REQUIRED" | "SYNTHETIC_FALLBACK";
            /** @enum {string} */
            state: "UNKNOWN" | "GRANTED" | "DENIED";
        };
        /**
         * @description Per-claim view across the five shareable claims, carried on both
         *     the 200 (why is a claim absent from the minted token) and the
         *     claim-gate 403 (what is still owed).
         */
        ClaimsStateView: {
            email: components["schemas"]["ClaimRequirementStateView"];
            firstName: components["schemas"]["ClaimRequirementStateView"];
            lastName: components["schemas"]["ClaimRequirementStateView"];
            staticAvatar: components["schemas"]["ClaimRequirementStateView"];
            animatedAvatar: components["schemas"]["ClaimRequirementStateView"];
        };
        /**
         * @description The browser side-trip that unblocks a claim-gated direct-issue:
         *     a short-lived, single-use bearer URL where the user authenticates when
         *     required, completes missing data, and manages consent. Open the URL and
         *     let the browser page guide the user.
         */
        ErrandHandoff: {
            /** @description Bearer key (`ernd_…`); also the status-poll path key. */
            errandKey: string;
            /**
             * Format: uri
             * @description Open this in the user's system browser.
             */
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /**
         * @description 403 body. For the claim-gate reasons (`ClaimConsentRequired`,
         *     `RequiredClaimDataMissing`) the `claims` view and the `errand`
         *     handoff are present; for every other reason only `reason` is set.
         */
        DirectIssueDeniedError: {
            /** @description Stable machine-readable reason code. */
            reason: string;
            claims?: components["schemas"]["ClaimsStateView"];
            errand?: components["schemas"]["ErrandHandoff"];
        };
        CreateErrandRequest: {
            /**
             * @description A current application access token (JWT) for the user. The token
             *     must be unexpired and its session must remain active.
             */
            accessToken: string;
        };
        CreateErrandResponse: {
            /**
             * @description The browser side-trip to open, or `null` when the account already
             *     satisfies the application's claim policy (nothing to consent to or
             *     complete) — in that case just direct-issue.
             */
            errand: components["schemas"]["ErrandHandoff"] | null;
            claims: components["schemas"]["ClaimsStateView"];
        };
        ErrandStatusResponse: {
            /** @enum {string} */
            status: "PENDING" | "COMPLETED" | "EXPIRED";
        };
        /**
         * @description Error response body. Known failures may include a stable `reason`.
         *     Some failures are status-only and have an empty body. A missing,
         *     malformed, or structurally invalid JSON body returns `InvalidBody`.
         */
        Error: {
            /** @description Stable machine-readable reason code. */
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Prevent storage of the credential-bearing response. */
        CredentialCacheControl: "no-store";
        /** @description Legacy cache instruction retained for credential responses. */
        CredentialPragma: "no-cache";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The API invocation path is operational and reports the deployed
             *     service identity. This response does not assert dependency,
             *     configuration, or business-capability readiness.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    directIssueAccessKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectIssueAccessKeyRequest"];
            };
        };
        responses: {
            /** @description Tokens issued. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectIssueAccessKeyResponse"];
                };
            };
            /**
             * @description Malformed request body. The `reason` distinguishes
             *     `InvalidAccessKeyIdentifier` (must use the canonical
             *     `acs_k_<UUID v4>` form) and `InvalidAccessKeySecret` (must use
             *     the canonical `acs_t_<64 lowercase hex chars>` form).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Reason `AccessKeyDirectDenied`: the access-key credential was
             *     rejected. Obtain a current credential before retrying.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The attempt was refused. The response `reason` distinguishes:
             *
             *     - `Layer1Denied`, `Layer2Denied`, `Layer3Denied` — application
             *       policy rejected the attempt.
             *     - `ApplicationNotActive` — the application is unavailable.
             *     - `AccountDisabled` or `AccountDeleted` — the account is
             *       unavailable for issuance.
             *     - `EmailDomainBlocked`, `EmailDomainRequiresSso`, or
             *       `SsoAuthorityConflict` — email-domain policy prevents issuance.
             *     - `ClaimConsentRequired` or `RequiredClaimDataMissing` — browser
             *       interaction is required before direct issuance can continue.
             *
             *     Claim-gate responses also include `claims` and an `errand` browser
             *     handoff. Open `errand.url`, wait or poll its status, then retry this
             *     request once after completion.
             */
            403: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectIssueDeniedError"];
                };
            };
            /** @description Application anchor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Reason `AuthorizationArtifactStale`: identity authority changed
             *     during the attempt. Retry the complete credential exchange.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many access-key attempts. Back off before retrying. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access-key issuance failed with an empty response body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access-key issuance is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    directIssuePublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectIssuePublicKeyRequest"];
            };
        };
        responses: {
            /** @description Tokens issued. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectIssueAccessKeyResponse"];
                };
            };
            /** @description Malformed request body or public-key assertion syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Reason `PublicKeyDirectDenied`: the credential or signed assertion
             *     was rejected without revealing whether the key exists or which
             *     principal owns it.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Application rule, Account lifecycle, email-domain policy, or claim
             *     requirements refused issuance. Claim-gate responses use the same
             *     `claims` and `errand` handoff as AccessKey issuance.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectIssueDeniedError"];
                };
            };
            /** @description Application anchor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The assertion `jti` was already seen, or identity authority changed
             *     during issuance. Sign a fresh assertion and retry the complete
             *     exchange.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many public-key attempts. Back off before retrying. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public-key issuance failed with an empty response body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public-key issuance is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    directIssueSteamTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectIssueSteamTicketRequest"];
            };
        };
        responses: {
            /** @description Tokens issued. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectIssueSteamTicketResponse"];
                };
            };
            /** @description Malformed request (e.g. invalid `steamAppId`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Steam rejected the ticket. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The attempt was refused. The response `reason` distinguishes:
             *
             *     - `Layer1Denied`, `Layer2Denied`, `Layer3Denied` — application
             *       policy rejected the attempt.
             *     - `ApplicationNotActive` — the application is unavailable.
             *     - `AccountDisabled` or `AccountDeleted` — the account is
             *       unavailable for issuance.
             *     - `EmailDomainBlocked`, `EmailDomainRequiresSso`, or
             *       `SsoAuthorityConflict` — email-domain policy prevents issuance.
             *     - `ClaimConsentRequired` or `RequiredClaimDataMissing` — browser
             *       interaction is required before direct issuance can continue.
             *
             *     Claim-gate responses also include `claims` and an `errand` browser
             *     handoff. Open `errand.url`, wait or poll its status, then acquire a
             *     fresh Steam ticket and retry once after completion.
             */
            403: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectIssueDeniedError"];
                };
            };
            /** @description Application anchor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Conflict. The response `reason` distinguishes:
             *
             *     - `ReplayProtectionAlreadySeen` — the ticket was already submitted
             *       or is being processed.
             *     - `AuthorizationArtifactStale` — identity authority changed during
             *       the attempt.
             *
             *     Acquire a fresh ticket before retrying either condition.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Too many Steam-ticket attempts. Back off before acquiring and
             *     submitting another ticket.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Steam ticket verification is temporarily unavailable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createErrand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateErrandRequest"];
            };
        };
        responses: {
            /**
             * @description Either the errand handoff to open, or `errand: null` when nothing is
             *     owed. `claims` always reports the per-claim state.
             */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateErrandResponse"];
                };
            };
            /** @description The access token is missing, malformed, expired, or no longer active. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The application or the account is disabled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    errandStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The `errand.errandKey` value from the 403 body. */
                errandKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current errand status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrandStatusResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
