"""Sudomimus Connect SDK.

Token-exchange client for the Sudomimus authentication platform: establish an
inquiry, poll its status, redeem it for application tokens, and fetch
localized application metadata. Includes client-auth JWT signing for
``/establish`` and token verification (via ``sudomimus-token``).
"""

from __future__ import annotations

from ._generated.models import (
    AuthenticationRuleAccessKeyDirectPayload,
    AuthenticationRuleBattleNetOAuthPayload,
    AuthenticationRuleConstraint,
    AuthenticationRuleConstraintAccessKeyDirect,
    AuthenticationRuleConstraintBattleNetOAuth,
    AuthenticationRuleConstraintDiscordOAuth,
    AuthenticationRuleConstraintEmailVerification,
    AuthenticationRuleConstraintEnterpriseFederationApplicationManaged,
    AuthenticationRuleConstraintEnterpriseFederationDomainManaged,
    AuthenticationRuleConstraintGitHubOAuth,
    AuthenticationRuleConstraintGoogleOAuth,
    AuthenticationRuleConstraintPasskeyReasoned,
    AuthenticationRuleConstraintPasskeyUsernameless,
    AuthenticationRuleConstraintSteamOpenId,
    AuthenticationRuleConstraintSteamTicket,
    AuthenticationRuleConstraintXOAuth,
    AuthenticationRuleDiscordOAuthPayload,
    AuthenticationRuleEmailVerificationPayload,
    AuthenticationRuleEnterpriseFederationApplicationManagedPayload,
    AuthenticationRuleEnterpriseFederationDomainManagedPayload,
    AuthenticationRuleGitHubOAuthPayload,
    AuthenticationRuleGoogleOAuthPayload,
    AuthenticationRulePasskeyReasonedPayload,
    AuthenticationRulePasskeyUsernamelessPayload,
    AuthenticationRuleSteamOpenIdPayload,
    AuthenticationRuleSteamTicketPayload,
    AuthenticationRuleXOAuthPayload,
    EstablishRequest,
    EstablishResponse,
    HealthResponse,
    InfoRequest,
    InfoResponse,
    RealizeRuleAccountAliasPayload,
    RealizeRuleConstraint,
    RealizeRuleConstraintAccountAlias,
    RealizeRuleConstraintEmail,
    RealizeRuleConstraintEveryone,
    RealizeRuleConstraintSectorSubject,
    RealizeRuleConstraintSteamId,
    RealizeRuleEmailPayload,
    RealizeRuleEveryonePayload,
    RealizeRuleSectorSubjectPayload,
    RealizeRuleSteamIdPayload,
    RedeemRequest,
    RedeemResponse,
    ReturnMethodCallback,
    ReturnMethodDeclaration,
    ReturnMethodReveal,
    ReturnMethodStatusPoll,
    StatusPollPendingResponse,
    StatusPollRealizedResponse,
    StatusPollRequest,
    StatusPollResponse,
)
from ._generated.models import Error as ConnectError
from .async_client import AsyncConnectClient
from .client import ConnectClient
from .client_auth import (
    ClientAuthSigner,
    ConnectClientAuth,
    ConnectClientAuthWithKey,
    ConnectClientAuthWithSigner,
    build_establish_client_jwt_claims,
    sha256_base64,
    sign_establish_client_jwt,
)
from .constants import (
    CLIENT_JWT_AUDIENCE,
    CLIENT_JWT_AUTH_SCHEME,
    CLIENT_JWT_DEFAULT_LIFETIME_SECONDS,
    CLIENT_JWT_MAX_LIFETIME_SECONDS,
    DEFAULT_PUBLIC_KEY_LOCALE,
    PRODUCTION_BASE_URL,
)
from .errors import ConnectApiError, ConnectConfigError

__all__ = [
    "CLIENT_JWT_AUDIENCE",
    "CLIENT_JWT_AUTH_SCHEME",
    "CLIENT_JWT_DEFAULT_LIFETIME_SECONDS",
    "CLIENT_JWT_MAX_LIFETIME_SECONDS",
    "DEFAULT_PUBLIC_KEY_LOCALE",
    "PRODUCTION_BASE_URL",
    "AsyncConnectClient",
    "AuthenticationRuleAccessKeyDirectPayload",
    "AuthenticationRuleBattleNetOAuthPayload",
    "AuthenticationRuleConstraint",
    "AuthenticationRuleConstraintAccessKeyDirect",
    "AuthenticationRuleConstraintBattleNetOAuth",
    "AuthenticationRuleConstraintDiscordOAuth",
    "AuthenticationRuleConstraintEmailVerification",
    "AuthenticationRuleConstraintEnterpriseFederationApplicationManaged",
    "AuthenticationRuleConstraintEnterpriseFederationDomainManaged",
    "AuthenticationRuleConstraintGitHubOAuth",
    "AuthenticationRuleConstraintGoogleOAuth",
    "AuthenticationRuleConstraintPasskeyReasoned",
    "AuthenticationRuleConstraintPasskeyUsernameless",
    "AuthenticationRuleConstraintSteamOpenId",
    "AuthenticationRuleConstraintSteamTicket",
    "AuthenticationRuleConstraintXOAuth",
    "AuthenticationRuleDiscordOAuthPayload",
    "AuthenticationRuleEmailVerificationPayload",
    "AuthenticationRuleGitHubOAuthPayload",
    "AuthenticationRuleGoogleOAuthPayload",
    "AuthenticationRulePasskeyReasonedPayload",
    "AuthenticationRulePasskeyUsernamelessPayload",
    "AuthenticationRuleSteamOpenIdPayload",
    "AuthenticationRuleSteamTicketPayload",
    "AuthenticationRuleXOAuthPayload",
    "AuthenticationRuleEnterpriseFederationApplicationManagedPayload",
    "AuthenticationRuleEnterpriseFederationDomainManagedPayload",
    "ClientAuthSigner",
    "ConnectApiError",
    "ConnectClient",
    "ConnectClientAuth",
    "ConnectClientAuthWithKey",
    "ConnectClientAuthWithSigner",
    "ConnectConfigError",
    "ConnectError",
    "EstablishRequest",
    "EstablishResponse",
    "HealthResponse",
    "InfoRequest",
    "InfoResponse",
    "RealizeRuleAccountAliasPayload",
    "RealizeRuleConstraint",
    "RealizeRuleConstraintAccountAlias",
    "RealizeRuleConstraintEmail",
    "RealizeRuleConstraintEveryone",
    "RealizeRuleConstraintSectorSubject",
    "RealizeRuleConstraintSteamId",
    "RealizeRuleEmailPayload",
    "RealizeRuleSectorSubjectPayload",
    "RealizeRuleSteamIdPayload",
    "RealizeRuleEveryonePayload",
    "RedeemRequest",
    "RedeemResponse",
    "ReturnMethodCallback",
    "ReturnMethodDeclaration",
    "ReturnMethodReveal",
    "ReturnMethodStatusPoll",
    "StatusPollPendingResponse",
    "StatusPollRealizedResponse",
    "StatusPollRequest",
    "StatusPollResponse",
    "build_establish_client_jwt_claims",
    "sha256_base64",
    "sign_establish_client_jwt",
]
