/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe for the Device service. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device-authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a device authorization session.
         * @description Creates a short-lived device authorization session for the application
         *     identified by `applicationAnchor`.
         *
         *     No client-auth JWT is required or accepted here. The application must
         *     already have an enabled Layer 3 `DEVICE_CODE` ReturnRule. The caller
         *     keeps `deviceCode` private and polls `/device-token`; the user sees
         *     `userCode` and approves the request at `verificationUri` or
         *     `verificationUriComplete`.
         *
         *     The client should wait at least `interval` seconds between
         *     `/device-token` polls. Polling faster can return `slow_down` with a
         *     larger interval.
         */
        post: operations["deviceAuthorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll and consume a device authorization session.
         * @description Polls the session identified by `deviceCode`. Pending and terminal
         *     refusal states are serialized as OAuth-style device-flow errors, not
         *     Sudomimus `{ "reason": "..." }` wire reasons.
         *
         *     A successful response consumes the device authorization session and
         *     returns a normal Sudomimus application access/refresh token pair.
         *     Repeating the same request after success cannot mint another pair.
         */
        post: operations["deviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ready: boolean;
            service: string;
            version: string;
        };
        /**
         * @description Public anchor identifying the application. Strict kebab-case, unique at
         *     application creation, and immutable after creation.
         */
        ApplicationAnchor: string;
        /**
         * @description High-entropy bearer secret for `/device-token`, returned only to the
         *     initiating client. Keep it private; do not display it to the browser
         *     user.
         */
        DeviceCode: string;
        /**
         * @description Short human-facing code shown by the client and confirmed in the
         *     browser. Uses the Crockford-style alphabet without ambiguous letters.
         */
        UserCode: string;
        DeviceAuthorizeRequest: {
            applicationAnchor: components["schemas"]["ApplicationAnchor"];
        };
        DeviceAuthorizeResponse: {
            applicationAnchor: components["schemas"]["ApplicationAnchor"];
            deviceCode: components["schemas"]["DeviceCode"];
            userCode: components["schemas"]["UserCode"];
            /**
             * Format: uri
             * @description Browser page where the user enters or confirms `userCode`.
             */
            verificationUri: string;
            /**
             * Format: uri
             * @description Browser URL pre-filled with `userCode`.
             */
            verificationUriComplete: string;
            /** @description Session lifetime in seconds. Default production value is 600. */
            expiresIn: number;
            /** @description Minimum polling interval in seconds. Default production value is 5. */
            interval: number;
        };
        DeviceTokenRequest: {
            deviceCode: components["schemas"]["DeviceCode"];
        };
        DeviceTokenResponse: {
            applicationAnchor: components["schemas"]["ApplicationAnchor"];
            /**
             * @description Short-lived access token (JWT). The application-visible user key is
             *     the `subject` (sector subject) claim. Claim fields such as
             *     `emailAddress`, `firstName`, and `lastName` are minted according to
             *     the application's claim policy and the user's standing grant.
             */
            accessToken: string;
            /**
             * @description Long-lived refresh token (JWT). Use Session API `/refresh` to rotate it
             *     and issue later access tokens.
             */
            refreshToken: string;
            claims: components["schemas"]["ClaimsStateView"];
        };
        /**
         * @description OAuth-style device-flow error body returned by `/device-token`.
         *     Polling clients should branch on `error`, not on Sudomimus wire
         *     `reason` symbols.
         */
        DeviceTokenError: {
            /** @enum {string} */
            error: "authorization_pending" | "slow_down" | "access_denied" | "expired_token" | "invalid_request" | "server_error";
            /** @description Present for `slow_down`; use this value for subsequent polls. */
            interval?: number;
        };
        /**
         * @description One shareable claim: what the application requests (`requirement`)
         *     joined with the user's standing decision (`state`). `UNKNOWN` means the
         *     user was never asked; `DENIED` means the user explicitly declined.
         */
        ClaimRequirementStateView: {
            /**
             * @description The developer's policy for the claim. `SYNTHETIC` guarantees the
             *     claim is present but permits a generated placeholder when the user
             *     has not shared real data.
             * @enum {string}
             */
            requirement: "OFF" | "OPTIONAL" | "REQUIRED" | "SYNTHETIC";
            /** @enum {string} */
            state: "UNKNOWN" | "GRANTED" | "DENIED";
        };
        /**
         * @description Per-claim view across the three shareable claims - why a claim is or is
         *     not present in the minted token.
         */
        ClaimsStateView: {
            email: components["schemas"]["ClaimRequirementStateView"];
            firstName: components["schemas"]["ClaimRequirementStateView"];
            lastName: components["schemas"]["ClaimRequirementStateView"];
        };
        /**
         * @description Error response body for non-polling validation and infrastructure
         *     failures. `/device-token` handler-level polling states use
         *     `DeviceTokenError` instead.
         */
        Error: {
            /** @description Stable machine-readable reason code. */
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    deviceAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceAuthorizeRequest"];
            };
        };
        responses: {
            /** @description Device authorization session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuthorizeResponse"];
                };
            };
            /** @description Malformed request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The application cannot start device authorization. The `reason`
             *     distinguishes:
             *
             *     - `ApplicationDisabled` - the application has been disabled.
             *     - `Layer3Denied` - the application does not currently have an
             *       enabled `DEVICE_CODE` ReturnRule.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Application anchor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenRequest"];
            };
        };
        responses: {
            /** @description Tokens issued and the device authorization session consumed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenResponse"];
                };
            };
            /**
             * @description Device-flow polling state or terminal client-visible refusal:
             *
             *     - `authorization_pending` - the user has not approved or denied the
             *       request yet. Continue polling after the current interval.
             *     - `slow_down` - the client is polling too quickly. Use the returned
             *       `interval` value for subsequent polls.
             *     - `access_denied` - the user denied the request, approval failed, or
             *       policy no longer allows token issuance.
             *     - `expired_token` - the device authorization session expired.
             *     - `invalid_request` - the `deviceCode` is unknown or has already
             *       been consumed.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenError"];
                };
            };
            /**
             * @description Token issuance failed after approval. The device authorization
             *     session is failed server-side and the client should stop polling.
             */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenError"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
