# generated by datamodel-codegen:
#   filename:  device.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class HealthResponse(BaseModel):
    ready: bool
    service: str
    version: str


class DeviceAuthorizeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )

    applicationAnchor: str = Field(
        ...,
        description="Public anchor identifying the application. Strict kebab-case, unique at\napplication creation, and immutable after creation.\n",
        max_length=64,
        min_length=3,
        pattern="^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$",
    )


class DeviceAuthorizeResponse(BaseModel):
    applicationAnchor: str = Field(
        ...,
        description="Public anchor identifying the application. Strict kebab-case, unique at\napplication creation, and immutable after creation.\n",
        max_length=64,
        min_length=3,
        pattern="^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$",
    )
    deviceCode: str = Field(
        ...,
        description="High-entropy bearer secret for `/device-token`, returned only to the\ninitiating client. Keep it private; do not display it to the browser\nuser.\n",
        pattern="^dvc_[0-9a-f]{64}$",
    )
    userCode: str = Field(
        ...,
        description="Short human-facing code shown by the client and confirmed in the\nbrowser. Uses the Crockford-style alphabet without ambiguous letters.\n",
        pattern="^[0-9ABCDEFGHJKMNPQRSTVWXYZ]{4}-[0-9ABCDEFGHJKMNPQRSTVWXYZ]{4}$",
    )
    verificationUri: str = Field(
        ...,
        description="Browser page where the user enters or confirms `userCode`.",
    )
    verificationUriComplete: str = Field(
        ...,
        description="Browser URL pre-filled with `userCode`.",
    )
    expiresIn: int = Field(
        ...,
        description="Session lifetime in seconds. Default production value is 600.",
        ge=1,
    )
    interval: int = Field(
        ...,
        description="Minimum polling interval in seconds. Default production value is 5.",
        ge=1,
    )


class DeviceTokenRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )

    deviceCode: str = Field(
        ...,
        description="High-entropy bearer secret for `/device-token`, returned only to the\ninitiating client. Keep it private; do not display it to the browser\nuser.\n",
        pattern="^dvc_[0-9a-f]{64}$",
    )


class Requirement(StrEnum):
    """
    The developer's policy for the claim. `SYNTHETIC` guarantees the
    claim is present but permits a generated placeholder when the user
    has not shared real data.

    """

    OFF = "OFF"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    SYNTHETIC = "SYNTHETIC"


class State(StrEnum):
    UNKNOWN = "UNKNOWN"
    GRANTED = "GRANTED"
    DENIED = "DENIED"


class ClaimRequirementStateView(BaseModel):
    """
    One shareable claim: what the application requests (`requirement`)
    joined with the user's standing decision (`state`). `UNKNOWN` means the
    user was never asked; `DENIED` means the user explicitly declined.

    """

    requirement: Requirement = Field(
        ...,
        description="The developer's policy for the claim. `SYNTHETIC` guarantees the\nclaim is present but permits a generated placeholder when the user\nhas not shared real data.\n",
    )
    state: State


class ClaimsStateView(BaseModel):
    """
    Per-claim view across the three shareable claims - why a claim is or is
    not present in the minted token.

    """

    email: ClaimRequirementStateView
    firstName: ClaimRequirementStateView
    lastName: ClaimRequirementStateView


class DeviceTokenResponse(BaseModel):
    applicationAnchor: str = Field(
        ...,
        description="Public anchor identifying the application. Strict kebab-case, unique at\napplication creation, and immutable after creation.\n",
        max_length=64,
        min_length=3,
        pattern="^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$",
    )
    accessToken: str = Field(
        ...,
        description="Short-lived access token (JWT). The application-visible user key is\nthe `subject` (sector subject) claim. Claim fields such as\n`emailAddress`, `firstName`, and `lastName` are minted according to\nthe application's claim policy and the user's standing grant.\n",
    )
    refreshToken: str = Field(
        ...,
        description="Long-lived refresh token (JWT). Use Connect `/refresh` to rotate it\nand issue later access tokens.\n",
    )
    claims: ClaimsStateView


class Error1(StrEnum):
    authorization_pending = "authorization_pending"
    slow_down = "slow_down"
    access_denied = "access_denied"
    expired_token = "expired_token"
    invalid_request = "invalid_request"
    server_error = "server_error"


class DeviceTokenError(BaseModel):
    """
    OAuth-style device-flow error body returned by `/device-token`.
    Polling clients should branch on `error`, not on Sudomimus wire
    `reason` symbols.

    """

    error: Error1
    interval: int | None = Field(
        None,
        description="Present for `slow_down`; use this value for subsequent polls.",
        ge=1,
    )


class Error(BaseModel):
    """
    Error response body for non-polling validation and infrastructure
    failures. `/device-token` handler-level polling states use
    `DeviceTokenError` instead.

    """

    reason: str | None = Field(None, description="Stable machine-readable reason code.")
