/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe for the Session service. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token and issue a new access token.
         * @description Issues a new access token AND a new refresh token, atomically
         *     invalidating the presented refresh token. The Session API implements
         *     OAuth 2.1 BCP §4.14.2 strict refresh-token rotation: every successful
         *     `/refresh` rotates the refresh token, and a later presentation of the
         *     parent token is treated as evidence of compromise.
         *
         *     On compromise, the entire refresh-token family is revoked and the
         *     caller must restart with its initial login flow: Connect inquiry,
         *     device authorization, native direct-issue, or another ordinary
         *     application-token issuance path.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether the session behind an access token is still valid.
         * @description Returns the revocation status of the refresh-token session that the
         *     supplied access token descends from. The access token is
         *     self-authenticating: its signature is verified against the issuing
         *     application's public key, so no client-auth JWT is required. The access
         *     token's own expiry is not enforced here; the answer describes the
         *     underlying session.
         */
        post: operations["introspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the session behind a refresh token.
         * @description Revokes the single session identified by the supplied refresh token.
         *     Possession of a genuine refresh token authorizes the revocation, so no
         *     client-auth JWT is required. The operation is idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke every session of an account for the calling application.
         * @description Revokes all refresh tokens belonging to the given account that were
         *     issued for the calling application. This is an application-authority
         *     action, so it requires a client-auth JWT with audience
         *     `sudomimus-session`. Revocation is scoped to the calling application;
         *     sessions of the same account under other applications are unaffected.
         */
        post: operations["revokeAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ready: boolean;
            service: string;
            version: string;
        };
        ClaimRequirementStateView: {
            /** @enum {string} */
            requirement: "OFF" | "OPTIONAL" | "REQUIRED" | "SYNTHETIC";
            /** @enum {string} */
            state: "UNKNOWN" | "GRANTED" | "DENIED";
        };
        ClaimsStateView: {
            email: components["schemas"]["ClaimRequirementStateView"];
            firstName: components["schemas"]["ClaimRequirementStateView"];
            lastName: components["schemas"]["ClaimRequirementStateView"];
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RefreshResponse: {
            claims: components["schemas"]["ClaimsStateView"];
            /** @description Newly issued short-lived access token JWT. */
            accessToken: string;
            /** @description Newly issued refresh token JWT; the presented token has been consumed. */
            refreshToken: string;
        };
        IntrospectRequest: {
            accessToken: string;
        };
        IntrospectResponse: {
            /** @enum {string} */
            status: "active" | "revoked" | "expired" | "not_found";
            recommendedRecheckSeconds: number;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LogoutResponse: {
            revoked: boolean;
        };
        RevokeAllRequest: {
            /** @description Application-visible sector subject (`sub`) for the account to revoke. */
            subject: string;
        };
        RevokeAllResponse: {
            revokedCount: number;
        };
        Error: {
            reason: string;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New access token and rotated refresh token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Reason `AccountNotFound` — the account behind the refresh token could not be resolved. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Refresh token rejected. The `reason` distinguishes:
             *
             *     - `RefreshTokenNotFound` — token cannot be resolved.
             *     - `RefreshTokenSuspended` — the refresh-token session is suspended.
             *     - `RefreshTokenExpired` — the token is past its `exp`.
             *     - `RefreshTokenFamilyCompromised` — the presented token had already been rotated; the whole family has now been revoked.
             *     - `RefreshTokenRotationRaceLost` — a concurrent rotation won the conditional write and the family was revoked.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The attempt was refused. The `reason` distinguishes:
             *
             *     - `AccountDisabled` — the account behind the refresh token is disabled.
             *     - `AccountDeleted` — the account has been erased.
             *     - `ClaimConsentRequired` — a REQUIRED claim is no longer satisfied by a standing grant.
             *     - `EmailDomainBlocked` — a verified adopted domain now blocks this account.
             *     - `EmailDomainRequiresSso` — a verified adopted domain now requires SSO and this session was not realized through the required connector.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    introspect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntrospectRequest"];
            };
        };
        responses: {
            /** @description Status of the session behind the access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntrospectResponse"];
                };
            };
            /** @description Access token missing, malformed, or with an invalid signature. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Revocation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeAllRequest"];
            };
        };
        responses: {
            /** @description Number of sessions revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeAllResponse"];
                };
            };
            /** @description Client-auth JWT missing, malformed, expired, or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
