/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Session invocation health and deployment identity. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationAnchor}/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the public signing keys for one application's tokens.
         * @description Returns the lifecycle-aware public JWK Set used to verify ordinary
         *     application access and refresh tokens. Select the key whose `kid`
         *     matches the JWT JOSE header. The set can contain PREPUBLISHED, ACTIVE,
         *     and still-published RETIRING keys; it never contains private key
         *     material or REVOKED keys. The set contains at most 32 keys.
         */
        get: operations["applicationJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token and issue a new access token.
         * @description Issues a new access token AND a new refresh token by conditionally
         *     advancing the same ApplicationSession's signed `rotationVersion`.
         *     The Session API implements
         *     OAuth 2.1 BCP §4.14.2 strict refresh-token rotation: every successful
         *     `/refresh` rotates the refresh token, and a later presentation of the
         *     previous signed version is treated as evidence of compromise unless it is a
         *     near-simultaneous retry inside the rotation grace window.
         *
         *     Inside that short grace window, if another request already advanced
         *     the same session by exactly one version and that winning state remains
         *     active, the retry deterministically reissues the exact winning refresh
         *     JWT and receives HTTP 200. Outside the grace window, for a version older
         *     than the immediately previous version, or when exact adoption cannot be
         *     proven, the ApplicationSession is terminally revoked and the caller must restart with
         *     its initial login flow: Connect inquiry, device authorization, native
         *     direct-issue, or another ordinary application-token issuance path.
         *
         *     This endpoint accepts only ApplicationSessions whose required issuance
         *     protocol is `APPLICATION`. OIDC sessions are
         *     rejected before account, authority, grace-adoption, or rotation work
         *     and must use the OIDC `/token` endpoint.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether the session behind an access token is still valid.
         * @description Strongly resolves the supplied access token's payload `sid` and returns
         *     the current effective status of that ApplicationSession. The token's
         *     `aud` and pairwise payload `sub` must exactly match the stored session.
         *     The access token is
         *     self-authenticating: its signature is verified against the issuing
         *     application's public key, so no client-auth JWT is required. The access
         *     token's own expiry is not enforced here; the answer describes the
         *     underlying session.
         */
        post: operations["introspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve current identity data shared with an application.
         * @description Accepts an ordinary application access token as a Bearer credential and
         *     returns current, consent-gated identity data for its live
         *     ApplicationSession. This endpoint accepts only sessions whose issuance
         *     protocol is `APPLICATION`; OIDC clients use the discovered OIDC
         *     `userinfo_endpoint` instead. Profile data is read live and is never
         *     copied from the access token.
         */
        get: operations["userinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claim-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve current identity-claim policy and consent state.
         * @description Accepts an ordinary application access token as a Bearer credential and
         *     returns the live policy requirement and standing consent state for each
         *     shareable UserInfo claim. This endpoint accepts only sessions whose
         *     issuance protocol is `APPLICATION`; OIDC clients use the custom
         *     `claim_state_endpoint` from OIDC discovery instead.
         */
        get: operations["claimState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the session behind a refresh token.
         * @description Revokes the single session identified by the supplied refresh token.
         *     Any genuine signed version whose `sid`, `aud`, `jti`, and
         *     `rotationVersion` bind to that session may authorize the revocation;
         *     accepting an older genuine version here does not make it refreshable.
         *     No client-auth JWT is required. The operation is idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke every session of an account for the calling application.
         * @description Advances the account/application revocation authority for the account
         *     identified by the supplied sector subject, then best-effort revokes
         *     currently enumerated application-session rows. This is an
         *     application-authority action, so it requires a client-auth JWT with audience
         *     `sudomimus-session`. Revocation is scoped to the calling application;
         *     sessions of the same account under other applications are unaffected.
         *     A successful response acknowledges the request with `revoked: true`.
         *     Unknown or out-of-sector subjects return the same acknowledgement to
         *     avoid an existence oracle. Cleanup results are never exposed publicly.
         *     Client authentication is evaluated against the raw request body before
         *     recursive request-body schema validation. Each signed request is
         *     at-most-once: its `jti` is consumed in a `/revoke-all`-specific replay
         *     namespace, and a transport retry must use a freshly signed client JWT.
         */
        post: operations["revokeAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationJsonWebKey: {
            /** @enum {string} */
            kty: "RSA";
            /** @description Base64url-encoded RSA modulus. */
            n: string;
            /** @description Base64url-encoded RSA public exponent. */
            e: string;
            /** @description Stable signing-key identifier copied into JWT JOSE headers. */
            kid: string;
            /** @enum {string} */
            use: "sig";
            /** @enum {string} */
            alg: "RS256";
        };
        ApplicationJwksResponse: {
            keys: components["schemas"]["ApplicationJsonWebKey"][];
        };
        HealthResponse: {
            /**
             * @description The API invocation path completed successfully.
             * @enum {string}
             */
            status: "ok";
            /** @description Stable runtime service identity. */
            service: string;
            /** @description Version from the deployed service's version manifest. */
            version: string;
        };
        ClaimRequirementStateView: {
            /** @enum {string} */
            requirement: "SYNTHETIC_ONLY" | "OFF" | "OPTIONAL" | "REQUIRED" | "SYNTHETIC_FALLBACK";
            /** @enum {string} */
            state: "UNKNOWN" | "GRANTED" | "DENIED";
        };
        ClaimsStateView: {
            email: components["schemas"]["ClaimRequirementStateView"];
            firstName: components["schemas"]["ClaimRequirementStateView"];
            lastName: components["schemas"]["ClaimRequirementStateView"];
            staticAvatar: components["schemas"]["ClaimRequirementStateView"];
            animatedAvatar: components["schemas"]["ClaimRequirementStateView"];
        };
        RefreshRequest: {
            /** @description Signed refresh credential carrying stable payload `sid`, exact version `jti`, and `rotationVersion`; it contains no user identifier. */
            refreshToken: string;
        };
        RefreshResponse: {
            claims: components["schemas"]["ClaimsStateView"];
            /** @description Newly issued short-lived access token JWT carrying payload `sid` and pairwise `sub` with a fresh `jti`. */
            accessToken: string;
            /** @description Newly issued refresh token JWT for the same payload `sid`, with a fresh `jti` and incremented `rotationVersion`; the presented version has been consumed. */
            refreshToken: string;
        };
        IntrospectRequest: {
            /** @description Signed access credential whose payload `sid` is strongly resolved; its own `exp` is intentionally ignored by introspection. */
            accessToken: string;
        };
        UserInfoResponse: {
            /** @description Pairwise sector subject for this application. */
            sub: string;
            /** Format: email */
            email?: string;
            email_verified?: boolean;
            name?: string;
            given_name?: string;
            family_name?: string;
            /** Format: uri */
            picture?: string;
            /**
             * Format: uri
             * @description Sudomimus private claim for the sector-scoped animated avatar URL.
             */
            picture_animated?: string;
        };
        UserInfoClaimStateView: {
            email: components["schemas"]["ClaimRequirementStateView"];
            given_name: components["schemas"]["ClaimRequirementStateView"];
            family_name: components["schemas"]["ClaimRequirementStateView"];
            picture: components["schemas"]["ClaimRequirementStateView"];
            picture_animated: components["schemas"]["ClaimRequirementStateView"];
        };
        ClaimStateResponse: {
            /** @description Pairwise sector subject for this application. */
            sub: string;
            claims: components["schemas"]["UserInfoClaimStateView"];
        };
        BearerError: {
            /** @enum {string} */
            error: "invalid_token";
        };
        IntrospectResponse: {
            /** @enum {string} */
            status: "active" | "revoked" | "expired" | "not_found";
            recommendedRecheckSeconds: number;
        };
        LogoutRequest: {
            /** @description Any genuine signed refresh-token version for the ApplicationSession to revoke. */
            refreshToken: string;
        };
        LogoutResponse: {
            revoked: boolean;
        };
        RevokeAllRequest: {
            /** @description Application-visible sector subject (`sub`) for the account to revoke. */
            subject: string;
        };
        RevokeAllResponse: {
            /**
             * @description Authority-safe acknowledgement of the revocation request.
             * @enum {boolean}
             */
            revoked: true;
        };
        /**
         * @description Error response body. A missing, malformed, or structurally invalid JSON
         *     request body returns `InvalidBody` without parser or
         *     validation-library detail. A documented status-only private failure has
         *     an empty response body instead.
         */
        Error: {
            reason: string;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Public cache lifetime bounded by the signing-key prepublication window. */
        PublicJwksCacheControl: string;
        /** @description Prevent storage of the credential-bearing response. */
        CredentialCacheControl: "no-store";
        /** @description Legacy cache instruction retained for credential responses. */
        CredentialPragma: "no-cache";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The API invocation path is operational and reports the deployed
             *     service identity. This response does not assert dependency,
             *     configuration, or business-capability readiness.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    applicationJwks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable public application identifier carried by token `aud`. */
                applicationAnchor: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public JWK Set for the application. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PublicJwksCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationJwksResponse"];
                };
            };
            /** @description The required application anchor path parameter is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Reason `ApplicationNotFound` — the application anchor is unknown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /**
             * @description New access token and rotated refresh token issued. A benign
             *     concurrent retry may also receive 200 by adopting the exact signed
             *     version created by the winning refresh inside the rotation grace window.
             */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Reason `AccountNotFound` — the account behind the refresh token could not be resolved. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Refresh token rejected. The `reason` distinguishes:
             *
             *     - `RefreshTokenInvalid` — the JWT is malformed, has an unsupported
             *       algorithm or issuer, lacks required claims, names an unknown
             *       application, or does not exactly bind to a stored ApplicationSession.
             *     - `RefreshTokenInvalidType` — the JWT is not a refresh token, or
             *       the stored session belongs to the OIDC issuance protocol.
             *     - `RefreshTokenInvalidSignature` — signature verification failed.
             *     - `RefreshTokenSuspended` — the ApplicationSession is suspended.
             *     - `RefreshTokenExpired` — the token is past its `exp`.
             *     - `RefreshTokenRevoked` — the ApplicationSession or one of its live
             *       authority bindings was revoked.
             *     - `RefreshTokenFamilyCompromised` — the signed version is stale and
             *       exact grace-window adoption did not apply; the ApplicationSession
             *       has now been terminally revoked.
             *
             *     A concurrent rotation race that cannot adopt the winning version also
             *     returns HTTP 401 and revokes the session, but intentionally carries
             *     an empty response body rather than exposing a public reason.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The attempt was refused. The `reason` distinguishes:
             *
             *     - `AccountDisabled` — the account behind the refresh token is disabled.
             *     - `AccountDeleted` — the account has been erased.
             *     - `ApplicationDisabled` — the application, parent sector, or parent organization no longer permits token issuance.
             *     - `ClaimConsentRequired` — a REQUIRED claim is no longer satisfied by a standing grant.
             *     - `RequiredClaimDataMissing` — the REQUIRED email claim is granted,
             *       but the account no longer owns a primary email address to issue.
             *     - `EmailDomainBlocked` — a verified adopted domain now blocks this account.
             *     - `EmailDomainRequiresSso` — a verified adopted domain now requires SSO and this session was not realized through the required connector.
             *     - `SsoAuthorityConflict` — verified adopted domains require distinct SSO connectors, so no refresh session can satisfy every domain authority until the conflict is repaired.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description `AuthorizationArtifactStale` — the email-identity or exact sector
             *     binding changed after refresh authorization was evaluated. Restart
             *     through an initial issuance flow so current identity and claim
             *     authority are evaluated before another ApplicationSession is used.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    introspect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntrospectRequest"];
            };
        };
        responses: {
            /** @description Status of the session behind the access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntrospectResponse"];
                };
            };
            /** @description Access token missing, malformed, or with an invalid signature. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    userinfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current application-visible identity data. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    /** @description Prevent shared-cache reuse across Bearer credentials. */
                    Vary?: "Authorization";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoResponse"];
                };
            };
            /** @description Bearer token missing, malformed, expired, inactive, or owned by another issuance protocol. */
            401: {
                headers: {
                    /** @description Bearer authentication challenge. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BearerError"];
                };
            };
        };
    };
    claimState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current application-visible claim state. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CredentialCacheControl"];
                    Pragma: components["headers"]["CredentialPragma"];
                    /** @description Prevent shared-cache reuse across Bearer credentials. */
                    Vary?: "Authorization";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimStateResponse"];
                };
            };
            /** @description Bearer token missing, malformed, expired, inactive, or owned by another issuance protocol. */
            401: {
                headers: {
                    /** @description Bearer authentication challenge. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BearerError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Revocation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeAllRequest"];
            };
        };
        responses: {
            /** @description Authority-safe revocation acknowledgement. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeAllResponse"];
                };
            };
            /**
             * @description Client-auth JWT missing, malformed, expired, invalid, or replayed.
             *     A retry after an uncertain response must use a freshly signed JWT
             *     with a new `jti`.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
