# generated by datamodel-codegen:
#   filename:  native.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class StatusPollRequest(BaseModel):
    pollToken: str = Field(
        ..., description="Opaque token issued when the flow was initiated."
    )


class Status(StrEnum):
    """
    Current status of the authentication flow.
    """

    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    EXPIRED = "EXPIRED"


class StatusPollResponse(BaseModel):
    status: Status = Field(
        ..., description="Current status of the authentication flow."
    )
    accessToken: str | None = Field(
        None,
        description="Application access token; present only when status is APPROVED.",
    )
    refreshToken: str | None = Field(
        None,
        description="Application refresh token; present only when status is APPROVED.",
    )


class Error(BaseModel):
    code: str = Field(..., description="Stable machine-readable error code.")
    message: str = Field(..., description="Human-readable error message.")
    requestId: str | None = Field(
        None, description="Identifier for correlating with platform logs."
    )
