# generated by datamodel-codegen:
#   filename:  native.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Status(StrEnum):
    """
    The API invocation path completed successfully.
    """

    ok = "ok"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status = Field(
        ..., description="The API invocation path completed successfully."
    )
    service: str = Field(..., description="Stable runtime service identity.")
    version: str = Field(
        ..., description="Version from the deployed service's version manifest."
    )


class DirectIssueAccessKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applicationAnchor: str = Field(
        ..., description="Public anchor identifying the integrating application."
    )
    accessKeyIdentifier: str = Field(
        ...,
        description="Canonical access-key identifier, including the mandatory\n`acs_k_` prefix followed by its UUID.\n",
        pattern="^acs_k_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    )
    accessKeySecret: str = Field(
        ...,
        description="Canonical access-key secret, including the mandatory `acs_t_`\nprefix followed by 64 lowercase hexadecimal characters (32\nrandom bytes). Returned only when the access key is issued.\n",
        pattern="^acs_t_[0-9a-f]{64}$",
    )


class DirectIssuePublicKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applicationAnchor: str = Field(
        ..., description="Public anchor identifying the integrating application."
    )


class DirectIssueSteamTicketRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applicationAnchor: str = Field(
        ..., description="Public anchor identifying the integrating application."
    )
    steamTicketHex: str = Field(
        ...,
        description='Hex-encoded Steam Web API auth ticket bytes returned from\n`ISteamUser::GetAuthTicketForWebApi("sudomimus")`. Hexadecimal\ncharacters are case-insensitive.\n',
        max_length=5120,
        min_length=2,
        pattern="^(?:[0-9a-fA-F]{2}){1,2560}$",
    )
    steamAppId: int = Field(
        ...,
        description="Steam App ID under which the ticket was generated. Must be\nallow-listed by the application's `STEAM_TICKET` authentication\nrule. Steam binds tickets to their issuing App ID; passing a\ndifferent value fails verification.\n",
        ge=1,
    )


class Requirement(StrEnum):
    """
    The developer's policy for the claim. `SYNTHETIC_ONLY` always
    emits the generated placeholder and never asks for real data.
    `SYNTHETIC_FALLBACK` guarantees the claim is present but uses a
    generated placeholder (a stand-in name, a proxy email, or a
    generated avatar) when the user has not shared real data. Unlike `REQUIRED`, neither
    synthetic mode blocks issuance or raises an errand.

    """

    SYNTHETIC_ONLY = "SYNTHETIC_ONLY"
    OFF = "OFF"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    SYNTHETIC_FALLBACK = "SYNTHETIC_FALLBACK"


class State(StrEnum):
    UNKNOWN = "UNKNOWN"
    GRANTED = "GRANTED"
    DENIED = "DENIED"


class ClaimRequirementStateView(BaseModel):
    """
    One shareable claim: what the application requests (`requirement`)
    joined with the user's standing decision (`state`). `UNKNOWN` means
    the user was never asked; `DENIED` means the user explicitly
    declined.

    """

    requirement: Requirement = Field(
        ...,
        description="The developer's policy for the claim. `SYNTHETIC_ONLY` always\nemits the generated placeholder and never asks for real data.\n`SYNTHETIC_FALLBACK` guarantees the claim is present but uses a\ngenerated placeholder (a stand-in name, a proxy email, or a\ngenerated avatar) when the user has not shared real data. Unlike `REQUIRED`, neither\nsynthetic mode blocks issuance or raises an errand.\n",
    )
    state: State


class ClaimsStateView(BaseModel):
    """
    Per-claim view across the five shareable claims, carried on both
    the 200 (why is a claim absent from the minted token) and the
    claim-gate 403 (what is still owed).

    """

    email: ClaimRequirementStateView
    firstName: ClaimRequirementStateView
    lastName: ClaimRequirementStateView
    staticAvatar: ClaimRequirementStateView
    animatedAvatar: ClaimRequirementStateView


class ErrandHandoff(BaseModel):
    """
    The browser side-trip that unblocks a claim-gated direct-issue:
    a short-lived, single-use bearer URL where the user authenticates when
    required, completes missing data, and manages consent. Open the URL and
    let the browser page guide the user.

    """

    errandKey: str = Field(
        ..., description="Bearer key (`ernd_…`); also the status-poll path key."
    )
    url: AnyUrl = Field(..., description="Open this in the user's system browser.")
    expiresAt: AwareDatetime


class DirectIssueDeniedError(BaseModel):
    """
    403 body. For the claim-gate reasons (`ClaimConsentRequired`,
    `RequiredClaimDataMissing`) the `claims` view and the `errand`
    handoff are present; for every other reason only `reason` is set.

    """

    reason: str = Field(..., description="Stable machine-readable reason code.")
    claims: ClaimsStateView | None = None
    errand: ErrandHandoff | None = None


class CreateErrandRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accessToken: str = Field(
        ...,
        description="A current application access token (JWT) for the user. The token\nmust be unexpired and its session must remain active.\n",
    )


class CreateErrandResponse(BaseModel):
    errand: ErrandHandoff | None = Field(
        ...,
        description="The browser side-trip to open, or `null` when the account already\nsatisfies the application's claim policy (nothing to consent to or\ncomplete) — in that case just direct-issue.\n",
    )
    claims: ClaimsStateView


class Status1(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"


class ErrandStatusResponse(BaseModel):
    status: Status1


class Error(BaseModel):
    """
    Error response body. Known failures may include a stable `reason`.
    Some failures are status-only and have an empty body. A missing,
    malformed, or structurally invalid JSON body returns `InvalidBody`.

    """

    reason: str | None = Field(None, description="Stable machine-readable reason code.")


class DirectIssueAccessKeyResponse(BaseModel):
    claims: ClaimsStateView
    applicationAnchor: str
    accessToken: str = Field(
        ...,
        description="Account credentials use media type\n`vnd.sudomimus.application-access+jwt`. Workload credentials use\n`vnd.sudomimus.workload-access+jwt` and add exact\n`act: {sub: <pairwise-workload-subject>}`. In both cases payload\n`sub` is the owner Account's pairwise sector subject, `sid`\nidentifies the session, and `jti` identifies this token instance.\nThe token contains no profile claims or raw Account/Workload\nidentifier; use Session API `/userinfo` for current shared data.\n",
    )
    refreshToken: str = Field(
        ...,
        description="Long-lived refresh token JWT with stable payload `sid`, version identifier `jti`, and positive `rotationVersion`. It contains no user identifier. Use Session API `/refresh` for renewal without re-presenting the access key.",
    )


class DirectIssueSteamTicketResponse(BaseModel):
    claims: ClaimsStateView
    applicationAnchor: str
    accessToken: str = Field(
        ...,
        description="Short-lived access token (JWT). Payload `sub` is the pairwise\nsector subject, `sid` identifies the session, and\n`jti` identifies this token instance. It contains no profile claims\nor raw account identifier; use Session API `/userinfo` for current\nshared identity data.\n",
    )
    refreshToken: str = Field(
        ...,
        description="Long-lived refresh token JWT with stable payload `sid`, version identifier `jti`, and positive `rotationVersion`. It contains no user identifier. Use Session API `/refresh` to obtain a new access token without re-acquiring a Steam ticket.",
    )
